import { readFileSync } from "node:fs";
import { join } from "node:path";
import Link from "next/link";
import { Rocket, GitCommit, Clock, Tag, ExternalLink } from "lucide-react";

export const dynamic = "force-dynamic";

/**
 * /admin/deployments — Phase O §5.9.
 * Uses the existing deployment tracking: public/version.json (generated by
 * scripts/generate-version.mjs on every build) + the UpdateManager flow
 * (/version.json polling + UpdateBanner). Shows the CURRENT deployment's
 * real build/commit/version/releasedAt. Deployment HISTORY requires Vercel
 * API access we don't have server-side — shown honestly as unavailable
 * rather than fabricated.
 */

export default async function AdminDeploymentsPage() {
  let v: {
    version?: string;
    commit?: string;
    buildId?: string;
    releasedAt?: string;
    env?: string;
    dirty?: boolean;
  } = {};
  try {
    v = JSON.parse(readFileSync(join(process.cwd(), "public", "version.json"), "utf8"));
  } catch {}

  const releasedAtStr = v.releasedAt
    ? new Date(v.releasedAt).toLocaleString("ru-RU")
    : "Недоступно";

  const ageStr = v.releasedAt ? timeAgo(new Date(v.releasedAt)) : "";

  return (
    <div>
      <div className="mb-6">
        <h1 className="mq-t-title text-xl" style={{ color: "var(--mq-text)" }}>Деплой</h1>
        <p className="mq-t-meta text-xs mt-1" style={{ color: "var(--mq-text-muted)" }}>
          Текущее развертывание и система обновлений
        </p>
      </div>

      {/* Current deployment */}
      <div
        className="rounded-2xl p-5 mb-6"
        style={{
          backgroundColor: "var(--mq-card)",
          border: "1px solid color-mix(in srgb, var(--mq-accent) 25%, var(--mq-border))",
        }}
      >
        <div className="flex items-center gap-3 mb-4">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ backgroundColor: "color-mix(in srgb, var(--mq-accent) 12%, transparent)" }}
          >
            <Rocket className="w-5 h-5" style={{ color: "var(--mq-accent)" }} />
          </div>
          <div className="min-w-0">
            <p className="mq-t-label text-sm" style={{ color: "var(--mq-text)" }}>
              Текущее развертывание
            </p>
            <p className="mq-t-meta text-xs" style={{ color: "var(--mq-text-muted)" }}>
              {v.buildId || "Недоступно"} {ageStr ? `· ${ageStr}` : ""}
            </p>
          </div>
          <span
            className="ml-auto px-2.5 py-1 rounded-full text-[11px] font-semibold shrink-0"
            style={{
              backgroundColor: "rgba(34,197,94,0.12)",
              color: "#22c55e",
            }}
          >
            ACTIVE
          </span>
        </div>

        <div className="grid sm:grid-cols-2 gap-3">
          <Field icon={Tag} label="Версия" value={v.version || "Недоступно"} />
          <Field icon={GitCommit} label="Commit" value={v.commit || "Недоступно"} mono />
          <Field icon={Rocket} label="Build ID" value={v.buildId || "Недоступно"} mono />
          <Field icon={Clock} label="Опубликовано" value={releasedAtStr} />
        </div>
      </div>

      {/* Update system status — the real machinery, not a second system */}
      <div className="rounded-2xl p-5" style={{ backgroundColor: "var(--mq-card)", border: "1px solid var(--mq-border)" }}>
        <p className="mq-t-label text-sm mb-3" style={{ color: "var(--mq-text)" }}>
          Система обновлений
        </p>
        <div className="space-y-2.5">
          <Mechanism
            step="1"
            title="Каждая сборка пишет version.json"
            detail="scripts/generate-version.mjs (prebuild) фиксирует commit, buildId и время публикации в /version.json"
          />
          <Mechanism
            step="2"
            title="Клиент опрашивает /version.json"
            detail="UpdateManager: раз в минуту + при возврате во вкладку; BroadcastChannel синхронизирует другие вкладки"
          />
          <Mechanism
            step="3"
            title="Баннер с согласием пользователя"
            detail="«Новая версия доступна» → [Обновить] очищает SW-кэши и перезагружает; [Позже] откладывает"
          />
          <Mechanism
            step="4"
            title="Состояние сохраняется"
            detail="Очередь, трек, позиция, громкость и настройки живут в persisted-сторе и переживают обновление"
          />
        </div>
        <p className="mq-t-meta text-[11px] mt-4" style={{ color: "var(--mq-text-muted)" }}>
          История развертываний требует доступа к Vercel API — раздел показывает
          только текущее развертывание, без выдуманных записей.
        </p>
      </div>
    </div>
  );
}

function Field({
  icon: Icon,
  label,
  value,
  mono,
}: {
  icon: React.ElementType;
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="flex items-center gap-3 px-3.5 py-2.5 rounded-xl" style={{ backgroundColor: "var(--mq-bg)" }}>
      <Icon className="w-4 h-4 shrink-0" style={{ color: "var(--mq-text-muted)" }} />
      <span className="text-xs flex-1" style={{ color: "var(--mq-text-muted)" }}>{label}</span>
      <span className={`text-sm truncate ${mono ? "font-mono" : ""}`} style={{ color: "var(--mq-text)" }}>
        {value}
      </span>
    </div>
  );
}

function Mechanism({ step, title, detail }: { step: string; title: string; detail: string }) {
  return (
    <div className="flex gap-3">
      <span
        className="w-6 h-6 rounded-lg flex items-center justify-center text-[11px] font-mono font-semibold shrink-0"
        style={{ backgroundColor: "color-mix(in srgb, var(--mq-accent) 12%, transparent)", color: "var(--mq-accent)" }}
      >
        {step}
      </span>
      <div className="min-w-0">
        <p className="text-sm" style={{ color: "var(--mq-text)" }}>{title}</p>
        <p className="mq-t-meta text-[11px] mt-0.5" style={{ color: "var(--mq-text-muted)" }}>{detail}</p>
      </div>
    </div>
  );
}

function timeAgo(date: Date): string {
  const diffMs = Date.now() - date.getTime();
  const minutes = Math.floor(diffMs / 60000);
  if (minutes < 1) return "только что";
  if (minutes < 60) return `${minutes} мин назад`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} ч назад`;
  const days = Math.floor(hours / 24);
  return `${days} дн назад`;
}
