import { NextRequest, NextResponse } from "next/server";
import { searchSCTracks, getSoundCloudClientId, type SCTrack } from "@/lib/soundcloud";
import { withRateLimit, RATE_LIMITS } from "@/lib/rate-limit";
import { RECOMMENDATIONS_CONFIG as CFG } from "@/config/recommendations";
import {
  normalizeGenre, estimateEnergy, detectLanguage,
  hasNoiseKeywords, titleHashtagGenreMismatch,
  fetchSCTrackRelated, getFromCache, setCache,
} from "@/lib/music-utils";

/**
 * "Моя волна" (My Wave) Radio API v2 — YouTube Music / Yandex Music style.
 *
 * v2 changes: Ported ALL content quality filters from recommendations API.
 * Previously radio had minimal filtering (only noise keywords + cover check),
 * letting through AI-generated tracks, promo spam, generic titles, URL stuffers,
 * and other low-quality content that recommendations already filtered.
 *
 * Generates the next batch of tracks for an infinite radio stream based on
 * the currently playing track and session context. Uses a two-stage system:
 *
 *   Stage 1 — Candidate Generation (50–100 tracks via related APIs + search)
 *   Stage 2 — Ranking with energy-aware diversity selection (top 10–12)
 *
 * GET /api/music/radio
 *   ?scTrackId=12345               (required) current SoundCloud track ID
 *   &historyScIds=111,222,333      (optional) recently played SC IDs
 *   &skippedGenres=pop,edm         (optional) genres user keeps skipping
 *   &skippedArtists=DJ Foo,Bar Baz (optional) artists user keeps skipping
 *   &likedArtists=Artist1,Artist2  (optional) artists user has liked
 *   &likedGenres=rock,indie        (optional) genres user has liked
 *   &lang=russian                  (optional) language preference
 *   &energy=medium                 (optional) desired energy level
 *   &recentSkipCount=3             (optional) number of consecutive recent skips
 *   &completedGenres=rock,indie    (optional) genres user completes (feedback)
 */

// ── In-memory cache (4 min TTL) ────────────────────────────────────────────────
const cache = new Map<string, { data: unknown; expiry: number }>();
const CACHE_TTL = 4 * 60 * 1000; // 4 minutes

// ══════════════════════════════════════════════════════════════════════════════
// CONTENT QUALITY FILTERS (ported from recommendations API v13)
// ══════════════════════════════════════════════════════════════════════════════

/** Promo / spam / low-effort content keywords */
const PROMO_SPAM_KEYWORDS = [
  "free download", "free beat", "free instrumental", "type beat", "type beat free",
  "subscribe", "follow me", "follow for", "link in bio", "link in desc",
  "buy now", "purchase", "shop now", "merch", "merchandise",
  "prod by", "produced by", "beat by", "made by ai", "ai generated",
  "suno", "udio", "ai music", "generated by", "cover by ai",
  "ai cover", "ai remix", "ai vocals", "chatgpt", "openai",
  "test", "testing", "mic test", "audio test", "sample", "raw recording",
  "untitled", "no name", "unnamed track", "demo version", "rough mix",
  "must hear", "best of", "top 50", "top 100", "playlist", "mixtape",
  "non stop", "nonstop", "back to back", "24 7", "non stop mix",
  "live set", "dj set", "live mix", "radio show", "podcast ep",
  "tutorial", "how to", "lesson", "course", "masterclass", "workshop",
  "ringtone", "notification", "alarm", "sms tone", "alert sound",
  "official audio", "official video", "lyric video", "lyrics video",
  "slowed", "sped up", "nightcore", "bass boost", "reverb mix",
  "explicit", "clean version", "radio edit", "album version",
  "out now", "available now", "stream now", "new song",
  "x original", "original song", "official song", "debut single",
];

/** Keywords that indicate AI-generated content */
const AI_GENERATED_KEYWORDS = [
  "suno", "udio", "suno ai", "udio ai", "ai song", "ai music", "ai generated",
  "made with ai", "created with ai", "generated with suno",
  "ai vocals", "ai cover", "ai remix", "chatgpt song",
  "made by ai", "ai beat", "ai producer", "ai artist",
];

/** Patterns indicating generic/boring titles */
const GENERIC_TITLE_PATTERNS = [
  /^(track \d+|untitled|no title|unknown)$/i,
  /^(beat \d+|instrumental \d+|song \d+)$/i,
  /^[a-z\d_]+$/,
  /^(.)\1{4,}$/,
];

/** Domains/URLs in titles = spam */
const DOMAIN_PATTERNS = [
  ".com", ".io", ".net", ".org", ".gg", ".co",
  "soundcloud.com", "spotify.com", "youtube.com",
  "instagram.com", "tiktok.com", "twitter.com",
  "linktr.ee", "lnk.bio", "bit.ly",
];

/** Remix/cover keywords for unknown-artist spam detection */
const REMIX_COVER_KEYWORDS = ["remix", "cover", "mashup", "bootleg", "flip", "reflip", "rework", "edit", "mix", "version", "vip mix", "re-edit", "dub", "instrumental"];

/** Genres with high spam ratio on SoundCloud */
const LOW_QUALITY_GENRES = [
  "deep house", "soulful house", "club house", "jackin house",
  "progressive house", "tech house",
];

// ── Content quality check functions ──

function hasPromoSpamKeywords(text: string): boolean {
  const lower = text.toLowerCase();
  return PROMO_SPAM_KEYWORDS.some(kw => lower.includes(kw));
}

function isAIGeneratedContent(text: string): boolean {
  const lower = text.toLowerCase();
  return AI_GENERATED_KEYWORDS.some(kw => lower.includes(kw));
}

function isGenericTitle(title: string): boolean {
  if (!title || title.trim().length < 2) return true;
  return GENERIC_TITLE_PATTERNS.some(p => p.test(title.trim()));
}

function titleContainsUrl(title: string): boolean {
  const lower = title.toLowerCase();
  return DOMAIN_PATTERNS.some(d => lower.includes(d));
}

function isSpamArtistName(artistName: string): boolean {
  const lower = artistName.toLowerCase().trim();
  if (lower.length < 2) return true;
  if (/^[^a-zA-Zа-яА-Я]+$/.test(lower)) return true;
  if (DOMAIN_PATTERNS.some(d => lower.includes(d))) return true;
  const specialRatio = [...lower].filter(c => /[^a-zA-Zа-яА-Я0-9\s]/.test(c)).length / lower.length;
  if (specialRatio > 0.25) return true;
  if (/(.)\1{5,}/.test(lower)) return true;
  return false;
}

function isLowQualityGenre(genre: string): boolean {
  const lower = (genre || "").toLowerCase().trim();
  return LOW_QUALITY_GENRES.some(lq => lower === lq || lower.includes(lq));
}

function isRemixFromUnknown(title: string, artist: string, likedArtists: Set<string>): boolean {
  const lower = title.toLowerCase();
  const hasRemix = REMIX_COVER_KEYWORDS.some(kw => lower.includes(kw));
  if (!hasRemix) return false;
  const artistLower = artist.toLowerCase().trim();
  for (const a of likedArtists) {
    if (artistLower.includes(a.toLowerCase()) || a.toLowerCase().includes(artistLower)) return false;
  }
  return true;
}

/**
 * Combined content quality score — returns 0-100.
 * Tracks scoring below QUALITY_THRESHOLD are filtered out entirely.
 */
function contentQualityScore(
  track: SCTrack,
  likedArtists: Set<string>,
): number {
  let score = 100;
  const title = (track.title || "").trim();
  const artist = (track.artist || "").trim();
  const titleLower = title.toLowerCase();
  const artistLower = artist.toLowerCase();
  const titleLen = title.length;
  const combined = `${title} ${artist}`.toLowerCase();

  // No title or too short
  if (titleLen < 3) return 0;
  if (titleLen < 5) score -= 30;

  // AI-generated content → instant reject
  if (isAIGeneratedContent(combined)) return 0;

  // Generic/boring title
  if (isGenericTitle(title)) score -= 50;

  // Title contains URL/domain → instant reject
  if (titleContainsUrl(title)) return 0;

  // Spam artist name
  if (isSpamArtistName(artist)) score -= 60;

  // Title is all caps (usually spam)
  if (title === title.toUpperCase() && titleLen > 3) score -= 25;

  // Excessive special characters
  if (titleLen > 5) {
    const specialCount = [...title].filter(c => /[^a-zA-Zа-яА-Я0-9\s]/.test(c)).length;
    if (specialCount / titleLen > 0.2) score -= 30;
    if (specialCount / titleLen > 0.35) score -= 40;
  }

  // Very long title (likely keyword stuffing)
  if (titleLen > 80) score -= 20;
  if (titleLen > 120) return 5;

  // Remix from unknown artist
  if (isRemixFromUnknown(title, artist, likedArtists)) score -= 35;

  // Preview-only from unknown artist
  if (!track.scIsFull) {
    let isLikedArtist = false;
    for (const a of likedArtists) {
      if (artistLower.includes(a.toLowerCase()) || a.toLowerCase().includes(artistLower)) {
        isLikedArtist = true;
        break;
      }
    }
    if (!isLikedArtist) score -= 30;
  }

  // Duration too short or too long
  if (track.duration > 0) {
    if (track.duration < 60) score -= 40;
    if (track.duration > 600) score -= 15;
    if (track.duration > 1200) score -= 40;
  }

  // No genre metadata
  if (!track.genre || track.genre.trim().length === 0) score -= 15;

  // Repetitive words in title
  const words = titleLower.split(/\s+/);
  const uniqueWords = new Set(words);
  if (words.length > 3 && uniqueWords.size < words.length * 0.5) score -= 20;

  // Title is just artist name + generic suffix
  if (titleLower.startsWith(artistLower) && titleLower.length < artistLower.length + 20) score -= 15;

  return Math.max(0, score);
}

// Minimum quality score for a track to pass filtering
const QUALITY_THRESHOLD = 45; // v14: raised from 40 to match recommendations config


// ── Fetch track metadata by ID (direct API, NOT text search) ─────────────
async function fetchSCTrackMetadata(scTrackId: number): Promise<{
  artist: string; genre: string; duration: number; energy: number;
} | null> {
  try {
    const clientId = await getSoundCloudClientId();
    if (!clientId) return null;
    const res = await fetch(
      `https://api-v2.soundcloud.com/tracks/${scTrackId}?client_id=${clientId}`,
      { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(8000) },
    );
    if (!res.ok) return null;
    const t = await res.json();
    const user = t.user as Record<string, unknown> | undefined;
    const duration = Math.round(((t.full_duration as number) || (t.duration as number) || 30000) / 1000);
    return {
      artist: ((user?.username as string) || "").toLowerCase().trim(),
      genre: (t.genre as string) || "",
      duration,
      energy: estimateEnergy({ duration } as SCTrack),
    };
  } catch {
    return null;
  }
}

// ── Internal candidate with provenance ─────────────────────────────────────────
type CandidateSource =
  | "current_related"    // From SC Related for the currently playing track
  | "history_related"    // From SC Related for a history track
  | "artist_search"      // Found via artist name search
  | "genre_year_search"  // Found via "{genre} {year}" search
  | "genre_search";       // Generic genre search fallback

interface Candidate {
  track: SCTrack;
  source: CandidateSource;
  /** Energy distance from the seed track (0 = identical) */
  energyDistance: number;
}

// ── Track output format ────────────────────────────────────────────────────────
interface RadioTrack {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration: number;
  cover: string;
  genre: string;
  audioUrl: string;
  previewUrl: string;
  source: "soundcloud";
  scTrackId: number;
  scStreamPolicy: string;
  scIsFull: boolean;
}

// ── Scoring ────────────────────────────────────────────────────────────────────
function scoreCandidate(
  candidate: Candidate,
  ctx: {
    currentArtist: string;
    currentGenre: string;
    currentEnergy: number;
    currentDuration: number;
    recentSkipCount: number;
    historyArtists: Set<string>;
    skippedArtists: Set<string>;
    skippedGenres: Set<string>;
    likedArtists: Set<string>;
    likedGenres: Set<string>;
    completedGenres: Set<string>;
    langPref: string | null;
  },
): number {
  let score = 0;
  const { track, source } = candidate;
  const trackGenre = normalizeGenre(track.genre || "");
  const trackArtist = (track.artist || "").toLowerCase().trim();

  // ── PRIMARY SIGNALS (actual similarity) ──
  if (source === "current_related") score += CFG.radio.relatedCurrent;
  else if (source === "history_related") score += CFG.radio.relatedHistory;

  // Same artist as current track → PENALTY
  if (trackArtist && trackArtist === ctx.currentArtist.toLowerCase().trim()) {
    score += CFG.radio.sameArtist; // -40
  }
  // Same artist as recently played → soft penalty
  if (trackArtist && ctx.historyArtists.has(trackArtist)) {
    score -= 15;
  }
  // Genre match with current track
  if (trackGenre && ctx.currentGenre) {
    const curNorm = normalizeGenre(ctx.currentGenre);
    if (trackGenre === curNorm || trackGenre.includes(curNorm) || curNorm.includes(trackGenre)) {
      score += CFG.radio.genreMatch;
    }
  }

  // ── ENERGY FLOW ──
  const energyDiff = estimateEnergy(track) - ctx.currentEnergy;
  if (energyDiff > 0 && energyDiff <= 0.3) {
    score += CFG.radio.energyFlowUp;
  } else if (energyDiff < 0 && energyDiff >= -0.3) {
    score += CFG.radio.energyFlowDown;
  } else if (Math.abs(energyDiff) <= 0.15) {
    score += CFG.radio.energyStable;
  }

  // ── LANGUAGE (user preference) ──
  if (ctx.langPref) {
    const trackText = `${track.title || ""} ${track.artist || ""}`;
    const trackLang = detectLanguage(trackText);
    if (trackLang === ctx.langPref) score += CFG.radio.languageMatch;

    // Language mismatch penalty (from recommendations v12)
    if (ctx.langPref === "russian" && trackLang === "english") score -= 15;
    if (ctx.langPref === "english" && trackLang === "russian") score -= 15;
  }

  // ── LIKED ARTISTS/GENRES (strong positive personalization) ──
  if (ctx.likedArtists.has(trackArtist)) score += CFG.radio.historyArtist * 1.5;
  if (trackGenre && ctx.likedGenres.has(trackGenre)) score += CFG.radio.genreMatch * 1.5;

  // ── COMPLETED GENRES (feedback signal — user actually listens to these) ──
  if (trackGenre && ctx.completedGenres.has(trackGenre)) {
    score += CFG.scoring.completedGenreBonus;
  }

  // ── QUALITY GATES ──
  if (track.scIsFull) score += CFG.radio.playability;
  if (track.cover) score += CFG.radio.coverArt;
  if (track.duration >= 120 && track.duration <= 360) score += 10;

  // ── DURATION SIMILARITY ──
  if (ctx.currentDuration > 0) {
    const durDiff = Math.abs((track.duration || 200) - ctx.currentDuration);
    if (durDiff <= 60) score += 10;
    else if (durDiff <= 120) score += 5;
  }

  // ── FEEDBACK (skip signals) ──
  if (ctx.skippedArtists.has(trackArtist)) score -= CFG.radio.skippedArtistPenalty;
  if (ctx.skippedGenres.has(trackGenre)) score -= CFG.radio.skippedGenrePenalty;

  // ── ANTI-SPAM ──
  const titleArtistNoise = `${track.title || ""} ${track.artist || ""}`.toLowerCase();
  if (hasNoiseKeywords(titleArtistNoise)) score -= CFG.radio.noisePenalty;
  if (titleHashtagGenreMismatch(track.title || "", [ctx.currentGenre])) score -= CFG.radio.noisePenalty / 2;

  // v14: Quality scoring — prefer tracks with proper titles, real artists, etc.
  // This supplements the hard filter above by scoring borderline content
  const radioTitle = (track.title || "").trim();
  const radioArtist = (track.artist || "").trim();
  const radioTitleLen = radioTitle.length;
  // Good title length (not too short, not too long)
  if (radioTitleLen >= 5 && radioTitleLen <= 60) score += 5;
  // Has genre metadata
  if (track.genre && track.genre.trim().length > 0) score += 3;
  // Reasonable duration (2-6 min = proper track)
  if (track.duration >= 120 && track.duration <= 360) score += 5;
  // Full playable track (massive bonus — preview-only from unknown artist is usually garbage)
  if (!track.scIsFull) score -= 25;

  // ── MOMENTUM PENALTY ──
  if (ctx.recentSkipCount >= CFG.radio.momentumSkipThreshold) {
    if (trackArtist && trackArtist === ctx.currentArtist.toLowerCase().trim()) {
      score -= CFG.radio.momentumPenalty;
    }
  }

  // ── SERENDIPITY — reward novel discovery tracks ──
  const trackArtistNorm = (track.artist || "").toLowerCase().trim();
  const isNewArtist = !ctx.historyArtists.has(trackArtistNorm)
    && trackArtistNorm !== ctx.currentArtist.toLowerCase().trim()
    && !ctx.likedArtists.has(trackArtistNorm);
  const isNewGenre = trackGenre && !ctx.likedGenres.has(trackGenre) && trackGenre !== normalizeGenre(ctx.currentGenre);
  if (isNewArtist && isNewGenre) score += CFG.scoring.serendipityBonus;
  else if (isNewArtist) score += Math.floor(CFG.scoring.serendipityBonus / 2);

  // ── FRESHNESS (confidence-proportional jitter) ──
  // Higher-confidence sources get less jitter for stable rankings
  const confidence = source === "current_related" ? 1.0
    : source === "history_related" ? 0.8
    : source === "artist_search" ? 0.6
    : 0.4;
  const maxJitter = confidence >= 0.8 ? CFG.scoring.highConfidenceJitter : CFG.scoring.maxJitter;
  score += (Math.random() - 0.5) * 2 * maxJitter;

  return score;
}

// ── Hard exclusion filter (v2 — with ALL content quality gates) ──────────────
function shouldExclude(
  track: SCTrack,
  ctx: {
    excludedScIds: Set<number>;
    skippedArtists: Set<string>;
    skippedGenres: Set<string>;
    currentGenre: string;
    likedArtists: Set<string>;
  },
): boolean {
  // Already in the session's played history
  if (ctx.excludedScIds.has(track.scTrackId)) return true;

  // Skipped artist
  const artist = (track.artist || "").toLowerCase().trim();
  if (artist && ctx.skippedArtists.has(artist)) return true;

  // Skipped genre
  const genre = normalizeGenre(track.genre || "");
  if (genre && ctx.skippedGenres.has(genre)) return true;

  // No cover art
  if (!track.cover) return true;

  // Too short to be a real track
  if (track.duration && track.duration < 30) return true;

  // v14: Content quality filter — now uses the same comprehensive quality check
  // as the recommendations API (contentQualityScore with threshold)
  // This is the second layer of defense after shouldExclude's own checks
  // Note: contentQualityScore is called separately in addCandidate with QUALITY_THRESHOLD

  return false;
}

// ── Energy-aware diversity selection ───────────────────────────────────────────
function selectWithEnergyDiversity(
  scored: { candidate: Candidate; score: number }[],
  currentEnergy: number,
  targetCount: { min: number; max: number },
): Candidate[] {
  const result: Candidate[] = [];
  const used = new Set<number>();
  const artistCount = new Map<string, number>();
  const MAX_PER_ARTIST = 1;
  const totalTarget = targetCount.min + Math.floor(Math.random() * (targetCount.max - targetCount.min + 1));

  const pick = (
    filterFn: (c: { candidate: Candidate; score: number }) => boolean,
    maxFromBucket: number,
  ) => {
    let picked = 0;
    for (const item of scored) {
      if (result.length >= totalTarget || picked >= maxFromBucket) return;
      if (used.has(item.candidate.track.scTrackId)) continue;
      if (!filterFn(item)) continue;
      const artist = (item.candidate.track.artist || "").toLowerCase().trim();
      if ((artistCount.get(artist) || 0) >= MAX_PER_ARTIST) continue;
      artistCount.set(artist, (artistCount.get(artist) || 0) + 1);
      result.push(item.candidate);
      used.add(item.candidate.track.scTrackId);
      picked++;
    }
  };

  const closeRange = CFG.radio.energyCloseRange;
  const shiftRange = CFG.radio.energyShiftRange;

  pick(
    (c) => c.candidate.energyDistance <= closeRange,
    CFG.radio.closeBucketMax,
  );
  pick(
    (c) => c.candidate.energyDistance > closeRange && c.candidate.energyDistance <= shiftRange,
    CFG.radio.shiftBucketMax,
  );
  pick(
    (c) => c.candidate.energyDistance > shiftRange,
    CFG.radio.wildcardBucketMax,
  );

  // Fill remaining slots with highest-scored unused tracks
  for (const item of scored) {
    if (result.length >= totalTarget) break;
    if (used.has(item.candidate.track.scTrackId)) continue;
    const artist = (item.candidate.track.artist || "").toLowerCase().trim();
    if ((artistCount.get(artist) || 0) >= MAX_PER_ARTIST) continue;
    artistCount.set(artist, (artistCount.get(artist) || 0) + 1);
    result.push(item.candidate);
    used.add(item.candidate.track.scTrackId);
  }

  return result.slice(0, totalTarget);
}

// ── Artist-aware interleaving ──
function interleaveRadioTracks(tracks: Candidate[]): Candidate[] {
  if (tracks.length <= 2) return tracks;
  const result: Candidate[] = [];
  const remaining = [...tracks];
  let lastArtist: string | null = null;

  while (remaining.length > 0) {
    let pickedIdx = -1;
    for (let i = 0; i < remaining.length; i++) {
      const artist = (remaining[i].track.artist || "").toLowerCase().trim();
      if (artist !== lastArtist) {
        pickedIdx = i;
        break;
      }
    }
    if (pickedIdx === -1) pickedIdx = 0;
    const picked = remaining.splice(pickedIdx, 1)[0];
    lastArtist = (picked.track.artist || "").toLowerCase().trim();
    result.push(picked);
  }
  return result;
}

// ── Map candidate to output track ──────────────────────────────────────────────
function mapToRadioTrack(candidate: Candidate): RadioTrack {
  const { track } = candidate;
  return {
    id: track.id,
    title: track.title,
    artist: track.artist,
    album: track.album,
    duration: track.duration,
    cover: track.cover,
    genre: track.genre,
    audioUrl: track.audioUrl,
    previewUrl: track.previewUrl,
    source: "soundcloud",
    scTrackId: track.scTrackId,
    scStreamPolicy: track.scStreamPolicy,
    scIsFull: track.scIsFull,
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN HANDLER
// ══════════════════════════════════════════════════════════════════════════════
async function handler(request: NextRequest) {
  const { searchParams } = new URL(request.url);

  // ── Parse parameters ──────────────────────────────────────────────────────
  const scTrackIdParam = searchParams.get("scTrackId");
  const historyScIdsParam = searchParams.get("historyScIds") || "";
  const skippedGenresParam = searchParams.get("skippedGenres") || "";
  const skippedArtistsParam = searchParams.get("skippedArtists") || "";
  const likedArtistsParam = searchParams.get("likedArtists") || "";
  const likedGenresParam = searchParams.get("likedGenres") || "";
  const langParam = searchParams.get("lang") || "";
  const energyParam = searchParams.get("energy") || "";
  const recentSkipCount = parseInt(searchParams.get("recentSkipCount") || "0", 10);
  const completedGenresParam = searchParams.get("completedGenres") || "";

  // Validate required parameter
  if (!scTrackIdParam) {
    return NextResponse.json(
      { error: "Missing required parameter: scTrackId" },
      { status: 400 },
    );
  }

  const scTrackId = Number(scTrackIdParam);
  if (isNaN(scTrackId) || scTrackId <= 0) {
    return NextResponse.json(
      { error: "Invalid scTrackId: must be a positive integer" },
      { status: 400 },
    );
  }

  // Parse optional parameters
  const historyScIds: number[] = historyScIdsParam
    .split(",")
    .filter(Boolean)
    .map(Number)
    .filter((n) => !isNaN(n) && n > 0);

  const excludedScIds = new Set<number>([scTrackId, ...historyScIds]);

  const skippedGenres = new Set(
    skippedGenresParam.split(",").filter(Boolean).map((g) => normalizeGenre(g)),
  );

  const skippedArtists = new Set(
    skippedArtistsParam.split(",").filter(Boolean).map((a) => a.toLowerCase().trim()),
  );

  const likedArtists = new Set(
    likedArtistsParam.split(",").filter(Boolean).map((a) => a.toLowerCase().trim()),
  );

  const likedGenres = new Set(
    likedGenresParam.split(",").filter(Boolean).map((g) => normalizeGenre(g)),
  );

  const completedGenres = new Set(
    completedGenresParam.split(",").filter(Boolean).map((g) => normalizeGenre(g)),
  );

  const langPref: "russian" | "english" | "latin" | null =
    langParam === "russian" || langParam === "english" || langParam === "latin"
      ? langParam
      : null;

  let energyPref: number | null = null;
  if (energyParam === "high") energyPref = 0.8;
  else if (energyParam === "medium") energyPref = 0.5;
  else if (energyParam === "low") energyPref = 0.2;

  // ── Cache check ───────────────────────────────────────────────────────────
  const cacheKey = `radio:${scTrackId}:${historyScIdsParam}:${skippedGenresParam}:${skippedArtistsParam}:${likedArtistsParam}:${likedGenresParam}:${langParam}:${energyParam}:${recentSkipCount}:${completedGenresParam}`;
  const cached = getFromCache(cacheKey, cache);
  if (cached) return NextResponse.json(cached);

  try {
    // ══════════════════════════════════════════════════════════════════════════
    // STEP 0: Fetch seed track metadata + history track metadata (parallel)
    // ══════════════════════════════════════════════════════════════════════════

    const currentTrackPromise = fetchSCTrackMetadata(scTrackId);

    const last2History = historyScIds.slice(0, 2);
    const historyMetadataPromises = last2History.map(
      (hid) => fetchSCTrackMetadata(hid),
    );

    const [currentTrackMeta, ...historyMetadataResults] = await Promise.allSettled([
      currentTrackPromise,
      ...historyMetadataPromises,
    ]);

    let currentArtist = "";
    let currentGenre = "";
    let currentEnergy = 0.5;
    let currentDuration = 200;

    if (currentTrackMeta.status === "fulfilled" && currentTrackMeta.value) {
      const ct = currentTrackMeta.value;
      currentArtist = ct.artist;
      currentGenre = ct.genre;
      currentEnergy = ct.energy;
      currentDuration = ct.duration;
    }

    if (energyPref !== null) {
      currentEnergy = currentEnergy * 0.6 + energyPref * 0.4;
    }

    const historyArtists = new Set<string>();
    for (const result of historyMetadataResults) {
      if (result.status === "fulfilled" && result.value) {
        const artist = result.value.artist;
        if (artist) historyArtists.add(artist);
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // STAGE 1: CANDIDATE GENERATION (target 50–100 candidates)
    // ══════════════════════════════════════════════════════════════════════════

    const allFetchPromises: Promise<SCTrack[]>[] = [];
    const sourceMap: CandidateSource[] = [];

    // ── Source 1: SC Related for CURRENT track (~20 tracks, HIGHEST quality)
    sourceMap.push("current_related");
    allFetchPromises.push(fetchSCTrackRelated(scTrackId));

    // ── Source 2: Genre discovery search (~15 tracks, increased from 10)
    if (currentGenre) {
      sourceMap.push("genre_search");
      allFetchPromises.push(searchSCTracks(`${currentGenre} new artists`, 15));
    }

    // ── Source 3: SC Related for last 2 history tracks (~20 each, up to 40)
    for (const hid of last2History) {
      sourceMap.push("history_related");
      allFetchPromises.push(fetchSCTrackRelated(hid));
    }

    // ── Source 4: "{genre} {year}" search (~15 tracks, increased from 10)
    const year = new Date().getFullYear();
    const genreYearQuery = currentGenre ? `${currentGenre} ${year}` : `new music ${year}`;
    sourceMap.push("genre_year_search");
    allFetchPromises.push(searchSCTracks(genreYearQuery, 15));

    // ── Source 5: "{genre} mix" search (~10 tracks)
    if (currentGenre) {
      sourceMap.push("genre_search");
      allFetchPromises.push(searchSCTracks(`${currentGenre} mix`, 10));
    }

    // ── Source 6: Liked artist search — top 3 artists (increased from 2)
    const topLikedArtists = [...likedArtists].slice(0, 3);
    for (const la of topLikedArtists) {
      sourceMap.push("artist_search");
      allFetchPromises.push(searchSCTracks(`"${la}"`, 10));
    }

    // ── Source 7: Liked genre search — top 3 genres (increased from 2)
    const topLikedGenres = [...likedGenres].slice(0, 3);
    for (const lg of topLikedGenres) {
      sourceMap.push("genre_search");
      allFetchPromises.push(searchSCTracks(`${lg} ${year}`, 8));
    }

    // ── Source 8: Completed genres bonus — search in genres user actually finishes
    const topCompletedGenres = [...completedGenres].slice(0, 2);
    for (const cg of topCompletedGenres) {
      sourceMap.push("genre_search");
      allFetchPromises.push(searchSCTracks(`${cg} best`, 5));
    }

    // Execute ALL fetches in parallel
    const fetchResults = await Promise.allSettled(allFetchPromises);

    // ── Aggregate candidates ────────────────────────────────────────────────
    const candidateMap = new Map<number, Candidate>();
    const candidateArtistCount = new Map<string, number>();

    const sourcePriority: Record<CandidateSource, number> = {
      current_related: 5,
      history_related: 4,
      artist_search: 3,
      genre_year_search: 2,
      genre_search: 1,
    };

    // Build exclude context once (used by both shouldExclude and contentQualityScore)
    const excludeCtx = {
      excludedScIds,
      skippedArtists,
      skippedGenres,
      currentGenre,
      likedArtists,
    };

    let filteredByQuality = 0;
    let filteredByHard = 0;

    const addCandidate = (track: SCTrack, source: CandidateSource) => {
      if (track.scTrackId === scTrackId) return;

      const trackArtistLower = (track.artist || "").toLowerCase().trim();
      if (trackArtistLower && currentArtist && trackArtistLower === currentArtist) return;

      // ── ARTIST FREQUENCY CAP ──
      const artistCount = candidateArtistCount.get(trackArtistLower) || 0;
      if (artistCount >= 3) return;
      candidateArtistCount.set(trackArtistLower, artistCount + 1);

      // ── HARD EXCLUSION FILTER (v2 — comprehensive) ──
      if (shouldExclude(track, excludeCtx)) {
        filteredByHard++;
        return;
      }

      // ── CONTENT QUALITY SCORE GATE ──
      const quality = contentQualityScore(track, likedArtists);
      if (quality < QUALITY_THRESHOLD) {
        filteredByQuality++;
        return;
      }

      // Dedup with source priority upgrade
      const existing = candidateMap.get(track.scTrackId);
      if (existing) {
        if ((sourcePriority[source] ?? 0) > (sourcePriority[existing.source] ?? 0)) {
          existing.source = source;
        }
        return;
      }

      const trackEnergy = estimateEnergy(track);
      candidateMap.set(track.scTrackId, {
        track,
        source,
        energyDistance: Math.abs(trackEnergy - currentEnergy),
      });
    };

    for (let i = 0; i < fetchResults.length; i++) {
      const result = fetchResults[i];
      const source = sourceMap[i];
      if (result.status === "fulfilled") {
        for (const track of result.value) {
          addCandidate(track, source);
        }
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // STAGE 2: RANKING & ENERGY-AWARE SELECTION
    // ══════════════════════════════════════════════════════════════════════════

    const scoredCandidates: { candidate: Candidate; score: number }[] = [];

    for (const [, candidate] of candidateMap) {
      const score = scoreCandidate(candidate, {
        currentArtist,
        currentGenre,
        currentEnergy,
        currentDuration,
        recentSkipCount,
        historyArtists,
        skippedArtists,
        skippedGenres,
        likedArtists,
        likedGenres,
        completedGenres,
        langPref,
      });

      scoredCandidates.push({ candidate, score });
    }

    scoredCandidates.sort((a, b) => b.score - a.score);

    const selected = selectWithEnergyDiversity(scoredCandidates, currentEnergy, {
      min: CFG.radio.targetMin,
      max: CFG.radio.targetMax,
    });

    const interleaved = interleaveRadioTracks(selected);

    const tracks = interleaved.map(mapToRadioTrack);

    // ── Build response ──────────────────────────────────────────────────────
    const responseData = {
      tracks,
      seedInfo: {
        artist: currentArtist || "Unknown",
        genre: currentGenre || "Unknown",
        energy: Math.round(currentEnergy * 100) / 100,
      },
      sessionHints: {
        recommendedEnergyDirection: currentEnergy < 0.4 ? "up" : currentEnergy > 0.7 ? "down" : "stable",
        diversityDebt: selected.filter(c => {
          const e = estimateEnergy(c.track);
          return Math.abs(e - currentEnergy) <= CFG.radio.energyCloseRange;
        }).length > selected.length * 0.6 ? "high" : "normal",
      },
      _meta: {
        candidatesGenerated: candidateMap.size,
        candidatesAfterScoring: scoredCandidates.length,
        selected: tracks.length,
        filteredByQuality,
        filteredByHard,
      },
    };

    setCache(cacheKey, responseData, cache, 100, CACHE_TTL);
    return NextResponse.json(responseData);
  } catch (err) {
    console.error("[radio] Unexpected error:", err);
    return NextResponse.json(
      { tracks: [], seedInfo: { artist: "Unknown", genre: "Unknown", energy: 0 } },
      { status: 200 },
    );
  }
}

export const GET = withRateLimit(RATE_LIMITS.heavy, handler);
