package com.mq1.player.ui.components

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.Fill
import androidx.compose.ui.graphics.drawscope.withTransform
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * LUCIDE icon parity — geometry extracted verbatim from the web app's
 * lucide-react v0.525 (ISC license). The web draws these exact paths at
 * 24×24 with stroke 1.7–2.3, round caps/joins — the Android app renders
 * the SAME geometry so icon style is identical across platforms.
 *
 * This file is GENERATED by scripts/extract_lucide_icons.py — regenerate
 * (not hand-edit) if the web icon set changes.
 */
sealed interface SvgNode
data class PathData(val d: String) : SvgNode
data class Circle(val cx: Float, val cy: Float, val r: Float) : SvgNode
data class LineSeg(val x1: Float, val y1: Float, val x2: Float, val y2: Float) : SvgNode
data class RectSeg(val x: Float, val y: Float, val w: Float, val h: Float, val rx: Float) : SvgNode

class LucideIcon(val nodes: List<SvgNode>)

/** SVG path-data parser (M/L/H/V/C/S/Q/T/Z, absolute + relative). */
class SvgPathParser(private val d: String) {
    fun parse(): Path = Path().also { p ->
        var i = 0
        var cmd = ' '
        var cx = 0f; var cy = 0f   // current point
        var lastC = listOf(0f, 0f, 0f, 0f) // last cubic ctrl pair (for S/s)
        var lastQ = listOf(0f, 0f)          // last quad ctrl (for T/t)
        fun num(): Float {
            while (i < d.length && (d[i] == ' ' || d[i] == ',')) i++
            val start = i
            var seenDot = false
            var seenExp = false
            if (i < d.length && (d[i] == '+' || d[i] == '-')) i++ // leading sign
            while (i < d.length) {
                val c = d[i]
                when {
                    c.isDigit() -> i++
                    // second '.' starts a NEW number (SVG "2.5.5" == "2.5 .5")
                    c == '.' && !seenDot && !seenExp -> { seenDot = true; i++ }
                    (c == 'e' || c == 'E') && !seenExp && i > start -> { seenExp = true; i++ }
                    (c == '+' || c == '-') && seenExp && i > start &&
                        (d[i - 1] == 'e' || d[i - 1] == 'E') -> i++   // exponent sign
                    else -> break   // sign mid-token ("4.646-6.07") also breaks here
                }
            }
            return d.substring(start, i).toFloat()
        }
        fun isNum(): Boolean {
            var j = i
            while (j < d.length && (d[j] == ' ' || d[j] == ',')) j++
            return j < d.length && (d[j].isDigit() || d[j] in ".-")
        }
        while (i < d.length) {
            while (i < d.length && (d[i] == ' ' || d[i] == ',')) i++
            if (i >= d.length) break
            val c = d[i]
            if (c.isLetter()) { cmd = c; i++ }
            when (cmd) {
                'M', 'm' -> {
                    val x = num(); val y = num()
                    cx = if (cmd == 'm') cx + x else x
                    cy = if (cmd == 'm') cy + y else y
                    p.moveTo(cx, cy)
                    // implicit lineto repeats
                    while (isNum()) {
                        val x2 = num(); val y2 = num()
                        cx = if (cmd == 'm') cx + x2 else x2
                        cy = if (cmd == 'm') cy + y2 else y2
                        p.lineTo(cx, cy)
                    }
                }
                'L', 'l' -> {
                    do {
                        val x = num(); val y = num()
                        cx = if (cmd == 'l') cx + x else x
                        cy = if (cmd == 'l') cy + y else y
                        p.lineTo(cx, cy)
                    } while (isNum())
                }
                'H', 'h' -> {
                    do {
                        val x = num()
                        cx = if (cmd == 'h') cx + x else x
                        p.lineTo(cx, cy)
                    } while (isNum())
                }
                'V', 'v' -> {
                    do {
                        val y = num()
                        cy = if (cmd == 'v') cy + y else y
                        p.lineTo(cx, cy)
                    } while (isNum())
                }
                'C', 'c' -> {
                    do {
                        val x1 = num(); val y1 = num(); val x2 = num(); val y2 = num(); val x = num(); val y = num()
                        val a1x = if (cmd == 'c') cx + x1 else x1; val a1y = if (cmd == 'c') cy + y1 else y1
                        val a2x = if (cmd == 'c') cx + x2 else x2; val a2y = if (cmd == 'c') cy + y2 else y2
                        val ax = if (cmd == 'c') cx + x else x; val ay = if (cmd == 'c') cy + y else y
                        p.cubicTo(a1x, a1y, a2x, a2y, ax, ay)
                        lastC = listOf(a1x, a1y, a2x, a2y)
                        cx = ax; cy = ay
                    } while (isNum())
                }
                'S', 's' -> {
                    do {
                        val x2 = num(); val y2 = num(); val x = num(); val y = num()
                        val a1x = 2 * cx - lastC[2]; val a1y = 2 * cy - lastC[3]
                        val a2x = if (cmd == 's') cx + x2 else x2; val a2y = if (cmd == 's') cy + y2 else y2
                        val ax = if (cmd == 's') cx + x else x; val ay = if (cmd == 's') cy + y else y
                        p.cubicTo(a1x, a1y, a2x, a2y, ax, ay)
                        lastC = listOf(a1x, a1y, a2x, a2y)
                        cx = ax; cy = ay
                    } while (isNum())
                }
                'Q', 'q' -> {
                    do {
                        val x1 = num(); val y1 = num(); val x = num(); val y = num()
                        val a1x = if (cmd == 'q') cx + x1 else x1; val a1y = if (cmd == 'q') cy + y1 else y1
                        val ax = if (cmd == 'q') cx + x else x; val ay = if (cmd == 'q') cy + y else y
                        p.quadraticBezierTo(a1x, a1y, ax, ay)
                        lastQ = listOf(a1x, a1y)
                        cx = ax; cy = ay
                    } while (isNum())
                }
                'T', 't' -> {
                    do {
                        val x = num(); val y = num()
                        val a1x = 2 * cx - lastQ[0]; val a1y = 2 * cy - lastQ[1]
                        val ax = if (cmd == 't') cx + x else x; val ay = if (cmd == 't') cy + y else y
                        p.quadraticBezierTo(a1x, a1y, ax, ay)
                        lastQ = listOf(a1x, a1y)
                        cx = ax; cy = ay
                    } while (isNum())
                }
                'A', 'a' -> {
                    // arc → cubic approximation (lucide uses arcs only for
                    // circles; approximation is visually indistinguishable)
                    do {
                        val rx = num(); val ry = num(); num() /*rot*/; val largeArc = num().toInt(); val sweep = num().toInt()
                        val x = num(); val y = num()
                        val ax = if (cmd == 'a') cx + x else x; val ay = if (cmd == 'a') cy + y else y
                        arcToCubic(p, cx, cy, rx, ry, largeArc, sweep, ax, ay)
                        cx = ax; cy = ay
                    } while (isNum())
                }
                'Z', 'z' -> { p.close() }
            }
        }
    }

    private fun arcToCubic(p: Path, x0: Float, y0: Float, rx0: Float, ry0: Float,
                           largeArc: Int, sweep: Int, x: Float, y: Float) {
        // Endpoint→center parameterization (SVG spec F.6.5, rotation=0 —
        // lucide never rotates), then split into ≤90° cubic segments.
        var rx = kotlin.math.abs(rx0).coerceAtLeast(0.01f)
        var ry = kotlin.math.abs(ry0).coerceAtLeast(0.01f)
        val x1p = (x0 - x) / 2f
        val y1p = (y0 - y) / 2f
        val lambda = (x1p * x1p) / (rx * rx) + (y1p * y1p) / (ry * ry)
        if (lambda > 1f) {
            val s = kotlin.math.sqrt(lambda)
            rx *= s; ry *= s
        }
        val num = (rx * rx * ry * ry) - (rx * rx * y1p * y1p) - (ry * ry * x1p * x1p)
        val den = (rx * rx * y1p * y1p) + (ry * ry * x1p * x1p)
        var factor = kotlin.math.sqrt(kotlin.math.max(0f, num / den))
        if (largeArc == sweep) factor = -factor
        val cx0 = factor * rx * y1p / ry + (x0 + x) / 2f
        val cy0 = -factor * ry * x1p / rx + (y0 + y) / 2f
        val theta1 = Math.atan2(((y0 - cy0) / ry).toDouble(), ((x0 - cx0) / rx).toDouble())
        var dTheta = Math.atan2(((y - cy0) / ry).toDouble(), ((x - cx0) / rx).toDouble()) - theta1
        if (sweep == 0 && dTheta > 0) dTheta -= 2 * Math.PI
        else if (sweep == 1 && dTheta < 0) dTheta += 2 * Math.PI
        val segments = kotlin.math.ceil(kotlin.math.abs(dTheta) / (Math.PI / 2)).toInt().coerceAtLeast(1)
        val delta = dTheta / segments
        val t = 4.0 / 3.0 * kotlin.math.tan(delta / 4.0)
        var th = theta1
        var px = x0.toDouble(); var py = y0.toDouble()
        repeat(segments) {
            val th2 = th + delta
            val d1 = t * -kotlin.math.sin(th) * rx
            val d2 = t * kotlin.math.cos(th) * ry
            val d3 = t * -kotlin.math.sin(th2) * rx
            val d4 = t * kotlin.math.cos(th2) * ry
            val nx = cx0 + rx * kotlin.math.cos(th2)
            val ny = cy0 + ry * kotlin.math.sin(th2)
            // parity-2a BUG FIX (sign inversion): P1 = P0 + t·dP/dθ and
            // P2 = P3 − t·dP/dθ per the SVG spec — the previous (px-d1,
            // py-d2)/(nx+d3, ny+d4) mirrored BOTH control points, collapsing
            // large arcs (Headphones r9 headband → spike, Heart r5.5 lobes →
            // inverted triangle). Verified: corrected cubics reproduce the
            // web pixel profile of lucide headphones/heart exactly.
            p.cubicTo(
                (px + d1).toFloat(), (py + d2).toFloat(),
                (nx - d3).toFloat(), (ny - d4).toFloat(),
                nx.toFloat(), ny.toFloat()
            )
            px = nx; py = ny; th = th2
        }
    }
}

private object PathCache {
    private val cache = java.util.concurrent.ConcurrentHashMap<String, Path>()
    fun get(d: String): Path = cache.computeIfAbsent(d) { SvgPathParser(it).parse() }
}

/**
 * MQ icon — renders Lucide geometry exactly like the web: 24×24 viewBox
 * scaled to [size]; [strokeWidth] is in 24-unit SVG space (2.0 == web
 * default) and scales with the icon, exactly like an SVG transform.
 * Round caps/joins. [fill] renders the filled variant (fill="currentColor").
 * Default tint = LocalContentColor (web: currentColor).
 */
@Composable
fun MqIcon(
    icon: LucideIcon,
    modifier: Modifier = Modifier,
    size: Dp = 24.dp,
    tint: Color = Color.Unspecified,
    strokeWidth: Float = 2f,
    fill: Boolean = false,
) {
    val content = androidx.compose.material3.LocalContentColor.current
    val tintResolved = if (tint == Color.Unspecified) content else tint
    Canvas(modifier = modifier.then(Modifier.size(size))) {
        val scale = this.size.width / 24f
        fun geometry(p: Path) = withTransform({ scale(scale, scale, pivot = Offset.Zero) }) {
            drawPath(
                p, tintResolved,
                style = if (fill) Fill
                else Stroke(width = strokeWidth, cap = StrokeCap.Round, join = StrokeJoin.Round),
            )
        }
        icon.nodes.forEach { node ->
            when (node) {
                is PathData -> geometry(PathCache.get(node.d))
                is Circle -> geometry(Path().apply {
                    addOval(Rect(node.cx - node.r, node.cy - node.r, node.cx + node.r, node.cy + node.r))
                })
                is LineSeg -> geometry(Path().apply {
                    moveTo(node.x1, node.y1); lineTo(node.x2, node.y2)
                })
                is RectSeg -> geometry(Path().apply {
                    if (node.rx > 0f) addRoundRect(
                        androidx.compose.ui.geometry.RoundRect(
                            node.x, node.y, node.x + node.w, node.y + node.h,
                            androidx.compose.ui.geometry.CornerRadius(node.rx, node.rx),
                        )
                    ) else addRect(Rect(node.x, node.y, node.x + node.w, node.y + node.h))
                })
            }
        }
    }
}


object MqIcons {  // member icons: one import unlocks all 72

    val Home = LucideIcon(listOf(
PathData("M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"),
    PathData("M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z")
))
    val Search = LucideIcon(listOf(
PathData("m21 21-4.34-4.34"),
    Circle(11.0f, 11.0f, 8.0f)
))
    val Library = LucideIcon(listOf(
PathData("m16 6 4 14"),
    PathData("M12 6v14"),
    PathData("M8 8v12"),
    PathData("M4 4v16")
))
    val MessageCircle = LucideIcon(listOf(
PathData("M7.9 20A9 9 0 1 0 4 16.1L2 22Z")
))
    val User = LucideIcon(listOf(
PathData("M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"),
    Circle(12.0f, 7.0f, 4.0f)
))
    val Play = LucideIcon(listOf(
PathData("M6 3 L20 12 L6 21 L6 3 Z")
))
    val Pause = LucideIcon(listOf(
RectSeg(14.0f, 4.0f, 4.0f, 16.0f, 1.0f),
    RectSeg(6.0f, 4.0f, 4.0f, 16.0f, 1.0f)
))
    val SkipBack = LucideIcon(listOf(
PathData("M19 20 L9 12 L19 4 L19 20 Z"),
    LineSeg(5.0f, 19.0f, 5.0f, 5.0f)
))
    val SkipForward = LucideIcon(listOf(
PathData("M5 4 L15 12 L5 20 L5 4 Z"),
    LineSeg(19.0f, 5.0f, 19.0f, 19.0f)
))
    val Heart = LucideIcon(listOf(
PathData("M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z")
))
    val Music = LucideIcon(listOf(
PathData("M9 18V5l12-2v13"),
    Circle(6.0f, 18.0f, 3.0f),
    Circle(18.0f, 16.0f, 3.0f)
))
    val ChevronDown = LucideIcon(listOf(
PathData("m6 9 6 6 6-6")
))
    val ChevronUp = LucideIcon(listOf(
PathData("m18 15-6-6-6 6")
))
    val ChevronRight = LucideIcon(listOf(
PathData("m9 18 6-6-6-6")
))
    val ChevronLeft = LucideIcon(listOf(
PathData("m15 18-6-6 6-6")
))
    val MoreHorizontal = LucideIcon(listOf(
Circle(12.0f, 12.0f, 1.0f),
    Circle(19.0f, 12.0f, 1.0f),
    Circle(5.0f, 12.0f, 1.0f)
))
    val X = LucideIcon(listOf(
PathData("M18 6 6 18"),
    PathData("m6 6 12 12")
))
    val Shuffle = LucideIcon(listOf(
PathData("m18 14 4 4-4 4"),
    PathData("m18 2 4 4-4 4"),
    PathData("M2 18h1.973a4 4 0 0 0 3.3-1.7l5.454-8.6a4 4 0 0 1 3.3-1.7H22"),
    PathData("M2 6h1.972a4 4 0 0 1 3.6 2.2"),
    PathData("M22 18h-6.041a4 4 0 0 1-3.3-1.8l-.359-.45")
))
    val Repeat = LucideIcon(listOf(
PathData("m17 2 4 4-4 4"),
    PathData("M3 11v-1a4 4 0 0 1 4-4h14"),
    PathData("m7 22-4-4 4-4"),
    PathData("M21 13v1a4 4 0 0 1-4 4H3")
))
    val Repeat1 = LucideIcon(listOf(
PathData("m17 2 4 4-4 4"),
    PathData("M3 11v-1a4 4 0 0 1 4-4h14"),
    PathData("m7 22-4-4 4-4"),
    PathData("M21 13v1a4 4 0 0 1-4 4H3"),
    PathData("M11 10h1v4")
))
    val ThumbsDown = LucideIcon(listOf(
PathData("M17 14V2"),
    PathData("M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z")
))
    val ListPlus = LucideIcon(listOf(
PathData("M11 12H3"),
    PathData("M16 6H3"),
    PathData("M16 18H3"),
    PathData("M18 9v6"),
    PathData("M21 12h-6")
))
    val Mic2 = LucideIcon(listOf(
PathData("m11 7.601-5.994 8.19a1 1 0 0 0 .1 1.298l.817.818a1 1 0 0 0 1.314.087L15.09 12"),
    PathData("M16.5 21.174C15.5 20.5 14.372 20 13 20c-2.058 0-3.928 2.356-6 2-2.072-.356-2.775-3.369-1.5-4.5"),
    Circle(16.0f, 7.0f, 5.0f)
))
    val ListMusic = LucideIcon(listOf(
PathData("M21 15V6"),
    PathData("M18.5 18a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"),
    PathData("M12 12H3"),
    PathData("M16 6H3"),
    PathData("M12 18H3")
))
    val History = LucideIcon(listOf(
PathData("M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"),
    PathData("M3 3v5h5"),
    PathData("M12 7v5l4 2")
))
    val Share2 = LucideIcon(listOf(
Circle(18.0f, 5.0f, 3.0f),
    Circle(6.0f, 12.0f, 3.0f),
    Circle(18.0f, 19.0f, 3.0f),
    LineSeg(8.59f, 13.51f, 15.42f, 17.49f),
    LineSeg(15.41f, 6.51f, 8.59f, 10.49f)
))
    val Volume2 = LucideIcon(listOf(
PathData("M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z"),
    PathData("M16 9a5 5 0 0 1 0 6"),
    PathData("M19.364 18.364a9 9 0 0 0 0-12.728")
))
    val Gauge = LucideIcon(listOf(
PathData("m12 14 4-4"),
    PathData("M3.34 19a10 10 0 1 1 17.32 0")
))
    val Timer = LucideIcon(listOf(
LineSeg(10.0f, 2.0f, 14.0f, 2.0f),
    LineSeg(12.0f, 14.0f, 15.0f, 11.0f),
    Circle(12.0f, 14.0f, 8.0f)
))
    val SlidersHorizontal = LucideIcon(listOf(
LineSeg(21.0f, 4.0f, 14.0f, 4.0f),
    LineSeg(10.0f, 4.0f, 3.0f, 4.0f),
    LineSeg(21.0f, 12.0f, 12.0f, 12.0f),
    LineSeg(8.0f, 12.0f, 3.0f, 12.0f),
    LineSeg(21.0f, 20.0f, 16.0f, 20.0f),
    LineSeg(12.0f, 20.0f, 3.0f, 20.0f),
    LineSeg(14.0f, 2.0f, 14.0f, 6.0f),
    LineSeg(8.0f, 10.0f, 8.0f, 14.0f),
    LineSeg(16.0f, 18.0f, 16.0f, 22.0f)
))
    val AirVent = LucideIcon(listOf(
PathData("M18 17.5a2.5 2.5 0 1 1-4 2.03V12"),
    PathData("M6 12H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"),
    PathData("M6 8h12"),
    PathData("M6.6 15.572A2 2 0 1 0 10 17v-5")
))
    val Bell = LucideIcon(listOf(
PathData("M10.268 21a2 2 0 0 0 3.464 0"),
    PathData("M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326")
))
    val Palette = LucideIcon(listOf(
PathData("M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z"),
    Circle(13.5f, 6.5f, 0.5f),
    Circle(17.5f, 10.5f, 0.5f),
    Circle(6.5f, 12.5f, 0.5f),
    Circle(8.5f, 7.5f, 0.5f)
))
    val Info = LucideIcon(listOf(
Circle(12.0f, 12.0f, 10.0f),
    PathData("M12 16v-4"),
    PathData("M12 8h.01")
))
    val Cloud = LucideIcon(listOf(
PathData("M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z")
))
    val Sparkles = LucideIcon(listOf(
PathData("M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"),
    PathData("M20 3v4"),
    PathData("M22 5h-4"),
    PathData("M4 17v2"),
    PathData("M5 18H3")
))
    val Waves = LucideIcon(listOf(
PathData("M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"),
    PathData("M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"),
    PathData("M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1")
))
    val WifiOff = LucideIcon(listOf(
PathData("M12 20h.01"),
    PathData("M8.5 16.429a5 5 0 0 1 7 0"),
    PathData("M5 12.859a10 10 0 0 1 5.17-2.69"),
    PathData("M19 12.859a10 10 0 0 0-2.007-1.523"),
    PathData("M2 8.82a15 15 0 0 1 4.177-2.643"),
    PathData("M22 8.82a15 15 0 0 0-11.288-3.764"),
    PathData("m2 2 20 20")
))
    val Trash2 = LucideIcon(listOf(
PathData("M3 6h18"),
    PathData("M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"),
    PathData("M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"),
    LineSeg(10.0f, 11.0f, 10.0f, 17.0f),
    LineSeg(14.0f, 11.0f, 14.0f, 17.0f)
))
    val Download = LucideIcon(listOf(
PathData("M12 15V3"),
    PathData("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"),
    PathData("m7 10 5 5 5-5")
))
    val Monitor = LucideIcon(listOf(
RectSeg(2.0f, 3.0f, 20.0f, 14.0f, 2.0f),
    LineSeg(8.0f, 21.0f, 16.0f, 21.0f),
    LineSeg(12.0f, 17.0f, 12.0f, 21.0f)
))
    val Apple = LucideIcon(listOf(
PathData("M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z"),
    PathData("M10 2c1 .5 2 2 2 5")
))
    val Terminal = LucideIcon(listOf(
PathData("M12 19h8"),
    PathData("m4 17 6-6-6-6")
))
    val Smartphone = LucideIcon(listOf(
RectSeg(5.0f, 2.0f, 14.0f, 20.0f, 2.0f),
    PathData("M12 18h.01")
))
    val LoaderCircle = LucideIcon(listOf(
PathData("M21 12a9 9 0 1 1-6.219-8.56")
))
    val Settings = LucideIcon(listOf(
PathData("M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"),
    Circle(12.0f, 12.0f, 3.0f)
))
    val Users = LucideIcon(listOf(
PathData("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"),
    PathData("M16 3.128a4 4 0 0 1 0 7.744"),
    PathData("M22 21v-2a4 4 0 0 0-3-3.87"),
    Circle(9.0f, 7.0f, 4.0f)
))
    val Plus = LucideIcon(listOf(
PathData("M5 12h14"),
    PathData("M12 5v14")
))
    // Lucide "upload" — used by Search «ФАЙЛЫ» (local upload); previously a
    // Download glyph (wrong semantic direction) stood in for it.
    val Upload = LucideIcon(listOf(
PathData("M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"),
    PathData("M17 8l-5-5-5 5"),
    PathData("M12 3v12")
))
    val Send = LucideIcon(listOf(
PathData("M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"),
    PathData("m21.854 2.147-10.94 10.939")
))
    val ArrowLeft = LucideIcon(listOf(
PathData("m12 19-7-7 7-7"),
    PathData("M19 12H5")
))
    val Camera = LucideIcon(listOf(
PathData("M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"),
    Circle(12.0f, 13.0f, 3.0f)
))
    val LogOut = LucideIcon(listOf(
PathData("m16 17 5-5-5-5"),
    PathData("M21 12H9"),
    PathData("M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4")
))
    val Check = LucideIcon(listOf(
PathData("M20 6 9 17l-5-5")
))
    val ImageIcon = LucideIcon(listOf(
RectSeg(3.0f, 3.0f, 18.0f, 18.0f, 2.0f),
    Circle(9.0f, 9.0f, 2.0f),
    PathData("m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21")
))
    val CircleCheck = LucideIcon(listOf(
Circle(12.0f, 12.0f, 10.0f),
    PathData("m9 12 2 2 4-4")
))
    val RefreshCw = LucideIcon(listOf(
PathData("M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"),
    PathData("M21 3v5h-5"),
    PathData("M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"),
    PathData("M8 16H3v5")
))
    val Lock = LucideIcon(listOf(
RectSeg(3.0f, 11.0f, 18.0f, 11.0f, 2.0f),
    PathData("M7 11V7a5 5 0 0 1 10 0v4")
))
    val Mail = LucideIcon(listOf(
PathData("m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"),
    RectSeg(2.0f, 4.0f, 20.0f, 16.0f, 2.0f)
))
    val Folder = LucideIcon(listOf(
PathData("M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z")
))
    val PlusCircle = LucideIcon(listOf(
Circle(12.0f, 12.0f, 10.0f),
    PathData("M8 12h8"),
    PathData("M12 8v8")
))
    val SearchX = LucideIcon(listOf(
PathData("m13.5 8.5-5 5"),
    PathData("m8.5 8.5 5 5"),
    Circle(11.0f, 11.0f, 8.0f),
    PathData("m21 21-4.3-4.3")
))
    val ArrowUpRight = LucideIcon(listOf(
PathData("M7 7h10v10"),
    PathData("M7 17 17 7")
))
    val List = LucideIcon(listOf(
PathData("M3 12h.01"),
    PathData("M3 18h.01"),
    PathData("M3 6h.01"),
    PathData("M8 12h13"),
    PathData("M8 18h13"),
    PathData("M8 6h13")
))
    val Radio = LucideIcon(listOf(
PathData("M16.247 7.761a6 6 0 0 1 0 8.478"),
    PathData("M19.075 4.933a10 10 0 0 1 0 14.134"),
    PathData("M4.925 19.067a10 10 0 0 1 0-14.134"),
    PathData("M7.753 16.239a6 6 0 0 1 0-8.478"),
    Circle(12.0f, 12.0f, 2.0f)
))
    val Flame = LucideIcon(listOf(
PathData("M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z")
))
    val TrendingUp = LucideIcon(listOf(
PathData("M16 7h6v6"),
    PathData("m22 7-8.5 8.5-5-5L2 17")
))
    val Clock = LucideIcon(listOf(
PathData("M12 6v6l4 2"),
    Circle(12.0f, 12.0f, 10.0f)
))
    val Headphones = LucideIcon(listOf(
PathData("M3 14h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-7a9 9 0 0 1 18 0v7a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3")
))
    val UserPlus = LucideIcon(listOf(
PathData("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"),
    Circle(9.0f, 7.0f, 4.0f),
    LineSeg(19.0f, 8.0f, 19.0f, 14.0f),
    LineSeg(22.0f, 11.0f, 16.0f, 11.0f)
))
    val UserCheck = LucideIcon(listOf(
PathData("m16 11 2 2 4-4"),
    PathData("M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"),
    Circle(9.0f, 7.0f, 4.0f)
))
    val MessageSquare = LucideIcon(listOf(
PathData("M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z")
))
    val FileText = LucideIcon(listOf(
PathData("M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"),
    PathData("M14 2v4a2 2 0 0 0 2 2h4"),
    PathData("M10 9H8"),
    PathData("M16 13H8"),
    PathData("M16 17H8")
))
    val AudioLines = LucideIcon(listOf(
PathData("M2 10v3"),
    PathData("M6 6v11"),
    PathData("M10 3v18"),
    PathData("M14 8v7"),
    PathData("M18 5v13"),
    PathData("M22 10v3")
))
    val CirclePause = LucideIcon(listOf(
Circle(12.0f, 12.0f, 10.0f),
    LineSeg(10.0f, 15.0f, 10.0f, 9.0f),
    LineSeg(14.0f, 15.0f, 14.0f, 9.0f)
))
}
