/**
 * @vitest-environment node
 *
 * Yandex adapter client tests (src/lib/yandex/adapter.ts):
 *   - HMAC signature contract — cross-checked against a vector generated by
 *     the REAL Python adapter (api/yandex_adapter.py) so the two sides can
 *     never drift apart
 *   - response parsing / error-code mapping
 *   - adapter_unreachable mapping on network failure
 *   - route fallback (/api/yandex_adapter → /api/yandex_adapter.py)
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

process.env.JWT_SECRET = "vector-test-secret-0123456789abcdef";
process.env.YANDEX_ADAPTER_URL = "http://adapter.test";

import {
  adapterProbe,
  adapterDeviceStart,
  adapterDevicePoll,
  adapterAccount,
  adapterBaseUrl,
} from "@/lib/yandex/adapter";
import { YandexError } from "@/lib/yandex/types";

const fetchMock = vi.fn();
vi.stubGlobal("fetch", fetchMock);

beforeEach(() => {
  fetchMock.mockReset();
});

function jsonResponse(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

describe("HMAC signature contract (parity with Python adapter)", () => {
  it("produces the exact signature the Python adapter verifies", async () => {
    let captured: { body: string; ts: string; sig: string; url: string } | null = null;
    fetchMock.mockImplementation(async (_url: string, init: RequestInit) => {
      captured = {
        url: _url,
        body: init.body as string,
        ts: init.headers?.["X-MQ-Timestamp"] as string,
        sig: init.headers?.["X-MQ-Signature"] as string,
      };
      return jsonResponse(200, { ok: true, data: { service: "mq-yandex-adapter", python: "3.12.14", yandex_music: "3.0.0" } });
    });

    await adapterProbe();

    // Reproduce the documented vector: the body is JSON.stringify({action:"probe"})
    // — signature depends on the exact bytes, so we verify the ALGORITHM by
    // recomputing the signature of the captured body and comparing.
    const crypto = await import("crypto");
    const derived = crypto
      .createHmac("sha256", "vector-test-secret-0123456789abcdef")
      .update("mq-yandex-adapter-v1")
      .digest();
    const expected = crypto
      .createHmac("sha256", derived)
      .update(`${captured!.ts}.${captured!.body}`)
      .digest("hex");
    expect(captured!.sig).toBe(expected);

    // Independent known vector (generated by the Python adapter itself):
    const vectorBody = '{"action":"device_start","device_name":"MQ"}';
    const vectorSig = crypto
      .createHmac("sha256", derived)
      .update(`1700000000.${vectorBody}`)
      .digest("hex");
    expect(vectorSig).toBe("075f7161eeb673211a97663eadfd407dd6d6cb9d21326d7a46cceac9e9fda3b9");
  });

  it("sends the timestamp within the acceptance window", async () => {
    fetchMock.mockResolvedValue(jsonResponse(200, { ok: true, data: { service: "x", python: "x", yandex_music: "x" } }));
    await adapterProbe();
    const init = fetchMock.mock.calls[0]![1] as RequestInit;
    const ts = Number(init.headers!["X-MQ-Timestamp"]);
    expect(Math.abs(ts - Math.floor(Date.now() / 1000))).toBeLessThanOrEqual(300);
  });
});

describe("adapter responses", () => {
  it("maps ok:false error codes to YandexError with status", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(401, { ok: false, error: { code: "yandex_unauthorized", message: "Токен истёк" } })
    );
    await expect(adapterAccount("tok")).rejects.toMatchObject({
      code: "yandex_unauthorized",
      status: 401,
      message: "Токен истёк",
    });
  });

  it("maps device_code_expired to 400", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(400, { ok: false, error: { code: "device_code_expired", message: "Код истёк" } })
    );
    await expect(adapterDevicePoll("dc")).rejects.toMatchObject({ code: "device_code_expired", status: 400 });
  });

  it("parses device_start data (user_code safe, device_code server-side)", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(200, {
        ok: true,
        data: { user_code: "AB12CD", verification_url: "https://ya.ru/device", device_code: "dvc", expires_in: 300, interval: 5 },
      })
    );
    const r = await adapterDeviceStart("MQ Player");
    expect(r.userCode).toBe("AB12CD");
    expect(r.verificationUrl).toBe("https://ya.ru/device");
    expect(r.deviceCode).toBe("dvc"); // caller (route) encrypts; never sent to browser
  });

  it("treats non-JSON responses as adapter_bad_response", async () => {
    fetchMock.mockResolvedValue(new Response("<html>404</html>", { status: 404 }));
    await expect(adapterAccount("tok")).rejects.toMatchObject({ code: "adapter_bad_response" });
  });

  it("falls back to the .py path when the primary route misses (production mode)", async () => {
    // The fallback only applies in production where the base URL is the
    // deployment origin — an explicit YANDEX_ADAPTER_URL override is canonical.
    const saved = process.env.YANDEX_ADAPTER_URL;
    delete process.env.YANDEX_ADAPTER_URL;
    (globalThis as { __ORIGIN__?: string }).__ORIGIN__ = undefined;
    try {
      fetchMock
        .mockResolvedValueOnce(new Response("Not Found", { status: 404 }))
        .mockResolvedValueOnce(
          jsonResponse(200, { ok: true, data: { service: "x", python: "x", yandex_music: "x" } })
        );
      const fakeReq = { nextUrl: { origin: "https://mq1.vercel.app" } } as never;
      await adapterProbe(fakeReq);
      expect(fetchMock).toHaveBeenCalledTimes(2);
      const firstUrl = fetchMock.mock.calls[0]![0] as string;
      expect(firstUrl).toBe("https://mq1.vercel.app/api/yandex_adapter");
      const secondUrl = fetchMock.mock.calls[1]![0] as string;
      expect(secondUrl).toBe("https://mq1.vercel.app/api/yandex_adapter.py");
    } finally {
      if (saved) process.env.YANDEX_ADAPTER_URL = saved;
    }
  });
});

describe("public_playlist action (tokenless public flow)", () => {
  it("sends ONLY {user_id, kind} — no token, no raw URL", async () => {
    let captured: { body: string } | null = null;
    fetchMock.mockImplementation(async (_url: string, init: RequestInit) => {
      captured = { body: init.body as string };
      return jsonResponse(200, { ok: true, data: { kind: 1293, uid: 1, title: "T", description: "", cover_url: "", owner_login: "music.partners", track_count: 0, tracks: [] } });
    });
    const { adapterPublicPlaylistTracks } = await import("@/lib/yandex/adapter");
    await adapterPublicPlaylistTracks("music.partners", 1293);
    const parsed = JSON.parse(captured!.body);
    expect(parsed).toEqual({ action: "public_playlist", user_id: "music.partners", kind: 1293 });
    expect(parsed.token).toBeUndefined();
    expect(parsed.url).toBeUndefined();
  });

  it("normalizes the playlist payload to camelCase (same shape as playlist_tracks)", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(200, {
        ok: true,
        data: {
          kind: 1293,
          uid: 111,
          title: "Публичный",
          description: "опис",
          cover_url: "https://c",
          owner_login: "music.partners",
          track_count: 1,
          tracks: [
            { position: 0, track_id: "42", album_id: "7", title: "Song", artists: ["A", "B"], album_title: "Al", album_id_full: "7", duration_ms: 123000, available: true },
          ],
        },
      })
    );
    const { adapterPublicPlaylistTracks } = await import("@/lib/yandex/adapter");
    const pl = await adapterPublicPlaylistTracks("music.partners", 1293);
    expect(pl).toEqual({
      kind: 1293,
      uid: 111,
      title: "Публичный",
      description: "опис",
      coverUrl: "https://c",
      ownerLogin: "music.partners",
      trackCount: 1,
      tracks: [
        { position: 0, trackId: "42", albumId: "7", title: "Song", artists: ["A", "B"], albumTitle: "Al", albumIdFull: "7", durationMs: 123000, available: true },
      ],
    });
  });

  it("maps yandex_geo_blocked to 503 with the region message", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(503, {
        ok: false,
        error: { code: "yandex_geo_blocked", message: "Яндекс.Музыка ограничивает доступ к плейлистам по региону." },
      })
    );
    const { adapterPublicPlaylistTracks } = await import("@/lib/yandex/adapter");
    await expect(adapterPublicPlaylistTracks("x", 1)).rejects.toMatchObject({
      code: "yandex_geo_blocked",
      status: 503,
    });
  });

  it("maps yandex_proxy_error (egress proxy failure) to 503, distinct from geo", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(503, {
        ok: false,
        error: { code: "yandex_proxy_error", message: "Импорт по ссылке временно недоступен с нашего сервера — попробуйте позже." },
      })
    );
    const { adapterPublicPlaylistTracks } = await import("@/lib/yandex/adapter");
    await expect(adapterPublicPlaylistTracks("x", 1)).rejects.toMatchObject({
      code: "yandex_proxy_error",
      status: 503,
      message: expect.stringContaining("нашего сервера"),
    });
  });

  it("maps yandex_not_found to 404 (private/missing playlist)", async () => {
    fetchMock.mockResolvedValue(
      jsonResponse(404, {
        ok: false,
        error: { code: "yandex_not_found", message: "Плейлист недоступен: не найден или скрыт настройками приватности." },
      })
    );
    const { adapterPublicPlaylistTracks } = await import("@/lib/yandex/adapter");
    await expect(adapterPublicPlaylistTracks("x", 1)).rejects.toMatchObject({
      code: "yandex_not_found",
      status: 404,
    });
  });
});

describe("network failures", () => {
  it("maps fetch rejection to adapter_unreachable", async () => {
    fetchMock.mockRejectedValue(new TypeError("fetch failed"));
    await expect(adapterAccount("tok")).rejects.toMatchObject({ code: "adapter_unreachable", status: 503 });
  });

  it("maps abort/timeout to adapter_unreachable", async () => {
    fetchMock.mockRejectedValue(new DOMException("The operation was aborted due to timeout", "TimeoutError"));
    await expect(adapterAccount("tok")).rejects.toMatchObject({ code: "adapter_unreachable" });
  });
});

describe("adapterBaseUrl", () => {
  it("prefers YANDEX_ADAPTER_URL override", () => {
    expect(adapterBaseUrl()).toBe("http://adapter.test");
  });
});

describe("YandexError shape", () => {
  it("carries code + status for structured handling", () => {
    const e = new YandexError("yandex_rate_limited", "Слишком много запросов", 429);
    expect(e.code).toBe("yandex_rate_limited");
    expect(e.status).toBe(429);
    expect(e.message).toContain("запросов");
  });
});
