"use client";

import { useState, useCallback, memo, useMemo, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Copy, Check, QrCode, Share2, Download, ExternalLink, Music } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { qrSvgString, drawQrToCanvas } from "@/lib/qr";

/**
 * ShareSheet — share dialog with a REAL QR code (task §12/§13).
 *
 * v72: the decorative hash-pattern "QR" is gone. The code is generated by
 * the vendored Nayuki encoder (src/lib/qr.ts) — ECL medium, 4-module quiet
 * zone, #000 on #fff, crispEdges SVG — and its scannability is proven by
 * a decode round-trip test against the real jsQR decoder
 * (src/__tests__/lib/qr.test.ts). The artwork renders BESIDE the code,
 * never on top of it (center logos break scanning).
 *
 * Features: real QR · Copy link · Download QR as PNG · native share ·
 * optional "Открыть в MQ Player" hand-off (deep link into the app).
 */

interface ShareSheetProps {
  isOpen: boolean;
  onClose: () => void;
  url: string;
  title: string;
  subtitle?: string;
  cover?: string;
  /** Deep link that opens the shared entity inside the app (e.g. /play?track=). */
  openInAppUrl?: string;
}

export const ShareSheet = memo(function ShareSheet({
  isOpen,
  onClose,
  url,
  title,
  subtitle,
  cover,
  openInAppUrl,
}: ShareSheetProps) {
  const [copied, setCopied] = useState(false);

  /* Escape closes (a11y: keyboard users must be able to dismiss dialogs). */
  useEffect(() => {
    if (!isOpen) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.stopPropagation();
        onClose();
      }
    };
    document.addEventListener("keydown", onKey, true);
    return () => document.removeEventListener("keydown", onKey, true);
  }, [isOpen, onClose]);

  /* Real QR — regenerated per URL. Pure string render; the encoder picks
     the smallest version that fits, which keeps density comfortable. */
  const qrMarkup = useMemo(
    () => (isOpen && url ? qrSvgString(url, { id: "share-qr-svg", size: 200, ariaLabel: `QR-код: ${title}` }) : ""),
    [isOpen, url, title]
  );

  const handleCopy = useCallback(() => {
    if (!navigator.clipboard) {
      toast({ title: "Браузер не поддерживает копирование", variant: "destructive" });
      return;
    }
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      toast({ title: "Ссылка скопирована" });
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {
      toast({ title: "Не удалось скопировать", variant: "destructive" });
    });
  }, [url, toast]);

  const handleNativeShare = useCallback(async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title, url });
      } catch {}
    }
  }, [title, url]);

  /* PNG export — raster straight from the QR matrix at 640px (quiet zone
     included), not a screenshot of the SVG. High contrast by construction. */
  const handleDownloadQR = useCallback(() => {
    try {
      const canvas = document.createElement("canvas");
      drawQrToCanvas(canvas, url, 640);
      const link = document.createElement("a");
      link.download = `qr-${title.replace(/[^\p{L}\p{N}]+/gu, "-").replace(/^-+|-+$/g, "").toLowerCase() || "mq"}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch {
      toast({ title: "Не удалось создать QR", variant: "destructive" });
    }
  }, [url, title]);

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="fixed inset-0 z-[200] flex items-end sm:items-center justify-center p-4"
          style={{ backgroundColor: "var(--mq-overlay-scrim)", backdropFilter: "blur(8px)", WebkitBackdropFilter: "blur(8px)" }}
          onClick={onClose}
          role="dialog"
          aria-modal="true"
          aria-label="Поделиться"
        >
          <motion.div
            initial={{ scale: 0.92, y: 24, opacity: 0 }}
            animate={{ scale: 1, y: 0, opacity: 1 }}
            exit={{ scale: 0.92, y: 24, opacity: 0 }}
            transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}
            className="w-full max-w-sm rounded-[20px] overflow-hidden"
            style={{
              backgroundColor: "var(--mq-card)",
              border: "1px solid var(--mq-border-thin)",
              boxShadow: "var(--mq-shadow-dramatic)",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Header — long-title contract: min-w-0 text + shrink-0 close */}
            <div className="flex items-center justify-between gap-3 px-5 py-4" style={{ borderBottom: "1px solid var(--mq-border-hairline)" }}>
              <div className="flex items-center gap-2.5 min-w-0 flex-1">
                <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0" style={{ backgroundColor: "color-mix(in srgb, var(--mq-accent) 15%, transparent)" }}>
                  <Share2 className="w-4 h-4" style={{ color: "var(--mq-accent)" }} />
                </div>
                <div className="min-w-0">
                  <h3 className="text-sm font-bold" style={{ color: "var(--mq-text)" }}>Поделиться</h3>
                  <p className="mq-t-meta-2 truncate" style={{ color: "var(--mq-text-muted)" }}>{title}</p>
                </div>
              </div>
              <button onClick={onClose} className="w-8 h-8 rounded-full flex items-center justify-center shrink-0" style={{ color: "var(--mq-text-muted)" }} aria-label="Закрыть">
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* QR — REAL, scannable, verified by decoder tests.
                Artwork sits BESIDE the code (never on top — center overlays
                destroy scan reliability). */}
            <div className="px-5 py-6 flex flex-col items-center gap-4">
              <div
                className="rounded-2xl p-3"
                style={{ backgroundColor: "#fff", boxShadow: "0 4px 16px rgba(0,0,0,0.2)" }}
                // Rendered via useMemo → qrSvgString (crispEdges SVG)
                dangerouslySetInnerHTML={{ __html: qrMarkup }}
              />
              {(subtitle || cover) && (
                <div className="flex items-center gap-3 max-w-full">
                  {cover ? (
                    <img src={cover} alt="" className="w-10 h-10 rounded-lg object-cover shrink-0" />
                  ) : (
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center shrink-0" style={{ backgroundColor: "var(--mq-surface-2)" }}>
                      <Music className="w-4 h-4" style={{ color: "var(--mq-text-muted)" }} />
                    </div>
                  )}
                  <div className="min-w-0 text-center sm:text-left">
                    {subtitle && <p className="text-xs font-semibold truncate" style={{ color: "var(--mq-text)" }}>{subtitle}</p>}
                    <p className="text-[11px] truncate" style={{ color: "var(--mq-text-muted)", maxWidth: 200 }}>{url.replace(/^https?:\/\//, "")}</p>
                  </div>
                </div>
              )}
              <p className="text-xs text-center" style={{ color: "var(--mq-text-muted)" }}>
                Наведите камеру телефона — откроется ссылка
              </p>
            </div>

            {/* Actions */}
            <div className="px-5 pb-5 space-y-2">
              {/* Copy link */}
              <motion.button
                onClick={handleCopy}
                className="w-full flex items-center gap-3 px-4 py-3 rounded-xl mq-icon-btn"
                style={{ ["--mq-rest-bg" as string]: "var(--mq-glass-bg)" }}
              >
                {copied ? <Check className="w-4 h-4" style={{ color: "var(--mq-accent)" }} /> : <Copy className="w-4 h-4" style={{ color: "var(--mq-text-muted)" }} />}
                <span className="text-sm flex-1 text-left truncate" style={{ color: "var(--mq-text)" }}>
                  {copied ? "Скопировано!" : url.replace(/^https?:\/\//, "")}
                </span>
              </motion.button>

              {/* Download QR */}
              <motion.button
                onClick={handleDownloadQR}
                className="w-full flex items-center gap-3 px-4 py-3 rounded-xl mq-icon-btn"
                style={{ ["--mq-rest-bg" as string]: "var(--mq-glass-bg)" }}
              >
                <QrCode className="w-4 h-4" style={{ color: "var(--mq-text-muted)" }} />
                <span className="text-sm flex-1 text-left" style={{ color: "var(--mq-text)" }}>Скачать QR код</span>
                <Download className="w-3.5 h-3.5" style={{ color: "var(--mq-text-muted)" }} />
              </motion.button>

              {/* Open in MQ Player — deep-link hand-off (track shares) */}
              {openInAppUrl && (
                <motion.button
                  onClick={() => { window.location.href = openInAppUrl; }}
                  className="w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors"
                  style={{ backgroundColor: "color-mix(in srgb, var(--mq-accent) 14%, transparent)", border: "1px solid color-mix(in srgb, var(--mq-accent) 30%, transparent)" }}
                >
                  <Music className="w-4 h-4" style={{ color: "var(--mq-accent)" }} />
                  <span className="text-sm font-semibold flex-1 text-left" style={{ color: "var(--mq-text)" }}>Открыть в MQ Player</span>
                  <ExternalLink className="w-3.5 h-3.5" style={{ color: "var(--mq-text-muted)" }} />
                </motion.button>
              )}

              {/* Native share (mobile) */}
              {typeof navigator !== "undefined" && "share" in navigator && (
                <motion.button
                  onClick={handleNativeShare}
                  className="w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors"
                  style={{ backgroundColor: "var(--mq-accent)", color: "var(--mq-text-on-accent, #fff)" }}
                >
                  <Share2 className="w-4 h-4" />
                  <span className="text-sm font-semibold flex-1 text-left">Поделиться через...</span>
                </motion.button>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
});
