#!/usr/bin/env python3
"""Generate MqThemes.kt: EXACT web palette port (themes.ts → Compose).
All 23 themes, hex-identical, plus the web type scale (mq-t-* → Manrope)
and web radius/spacing tokens. Central design system for visual parity."""
import re

src = open("/home/z/my-project/src/lib/themes.ts").read()
# strip ALL comments (full-line + trailing). Safe: no string literal in this
# file contains "//" (hex/rgba/gradient values only — verified above).
clean = re.sub(r"//[^\n]*", "", src)

themes = re.findall(
    r'([\w-]+):\s*\{\s*id:\s*"([\w-]+)",\s*name:\s*"([^"]+)",\s*'
    r'background:\s*"([^"]+)",\s*card:\s*"([^"]+)",\s*cardHover:\s*"([^"]+)",\s*'
    r'accent:\s*"([^"]+)",\s*text:\s*"([^"]+)",\s*textMuted:\s*"([^"]+)",\s*'
    r'border:\s*"([^"]+)",\s*inputBg:\s*"([^"]+)",\s*playerBg:\s*"([^"]+)",\s*'
    r'navBg:\s*"([^"]+)"', clean)

assert len(themes) == 23, f"expected 23 themes, got {len(themes)}"

def c(hexstr):
    h = hexstr.lstrip("#")
    if len(h) == 6:
        return f"Color(0xFF{h.upper()})"
    if len(h) == 8:  # CSS #RRGGBBAA → Compose ARGB
        return f"Color(0x{h[6:8].upper()}{h[0:6].upper()})"
    raise ValueError(hexstr)

def colorLit(s):
    """Any CSS color in themes.ts → Kotlin Color literal (hex or rgba)."""
    s = s.strip()
    if s.startswith("#"):
        return c(s)
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)", s)
    if m:
        r, g, b, a = int(m[1]), int(m[2]), int(m[3]), float(m[4])
        ai = round(a * 255)
        return f"Color(0x{ai:02X}{r:02X}{g:02X}{b:02X})"
    raise ValueError(s)

def ident(key):
    # Kotlin object name per theme (CamelCase of web name)
    return "".join(p.capitalize() for p in re.split(r"[-_]", key))

lines = []
lines.append("package com.mq1.player.ui.theme\n")
lines.append("import androidx.compose.foundation.isSystemInDarkTheme")
lines.append("import androidx.compose.material3.ColorScheme")
lines.append("import androidx.compose.material3.darkColorScheme")
lines.append("import androidx.compose.material3.lightColorScheme")
lines.append("import androidx.compose.runtime.Composable")
lines.append("import androidx.compose.ui.graphics.Color\n")
lines.append("/**")
lines.append(" * MQ DESIGN SYSTEM — exact port of the web `src/lib/themes.ts`.")
lines.append(" * GENERATED by scripts/gen_mq_themes.py from the web source of truth;")
lines.append(" * every hex is byte-identical to https://mq1.vercel.app.")
lines.append(" * 23 themes: pick by id, same ids as the web store.")
lines.append(" */")
lines.append("data class MqPalette(")
lines.append("    val id: String,")
lines.append("    val name: String,")
lines.append("    val background: Color,")
lines.append("    val surface: Color,          // web --mq-card")
lines.append("    val surfaceHigh: Color,      // web --mq-card-hover")
lines.append("    val accent: Color,")
lines.append("    val text: Color,")
lines.append("    val textMuted: Color,")
lines.append("    val outline: Color,         // web --mq-border")
lines.append("    val inputBg: Color,")
lines.append("    val playerBg: Color,")
lines.append("    val navBg: Color,           // web --mq-nav-bg (last 2 hex = alpha)")
lines.append("    val isDark: Boolean = true,")
lines.append("    val onAccent: Color = Color(0xFFFFFFFF),")
lines.append(")\n")

for key, tid, name, bg, card, hover, accent, text, muted, border, input, player, nav in themes:
    isdark = "true" if key != "daylight" else "false"
    onaccent = "Color(0xFFFFFFFF)"
    if key == "midnight":
        onaccent = "Color(0xFF000000)"  # white accent → dark icons on it
    lines.append(f"private val _{ident(key)} = MqPalette(")
    lines.append(f'    id = "{tid}", name = "{name}",')
    lines.append(f"    background = {colorLit(bg)}, surface = {colorLit(card)},")
    lines.append(f"    surfaceHigh = {colorLit(hover)}, accent = {colorLit(accent)},")
    lines.append(f"    onAccent = {onaccent},")
    lines.append(f"    text = {colorLit(text)}, textMuted = {colorLit(muted)},")
    lines.append(f"    outline = {colorLit(border)}, inputBg = {colorLit(input)},")
    lines.append(f"    playerBg = {colorLit(player)}, navBg = {colorLit(nav)},")
    lines.append(f"    isDark = {isdark},")
    lines.append(")\n")

order = ", ".join(f"_{ident(k)}" for k, *_ in themes)
lines.append(f"val mqThemes: List<MqPalette> = listOf({order})\n")
lines.append("fun paletteById(id: String): MqPalette =")
lines.append('    mqThemes.firstOrNull { it.id == id } ?: mqThemes.first()\n')
lines.append("""
/** Raw web palette access for components that read tokens the M3 scheme
 *  does not carry (inputBg, playerBg, navBg…). Provided by MainActivity. */
val LocalMqPalette = androidx.compose.runtime.staticCompositionLocalOf<MqPalette> {
    error("MqPalette not provided — wrap the tree in CompositionLocalProvider(LocalMqPalette to …)")
}

/** Resolves the palette exactly like mqColorScheme (dark-mode fallbacks). */
@Composable
fun currentMqPalette(themeId: String, darkMode: String): MqPalette {
    val systemDark = isSystemInDarkTheme()
    val dark = when (darkMode) {
        "light" -> false
        "dark" -> true
        else -> systemDark
    }
    val palette = paletteById(themeId).let {
        if (!dark && it.isDark && it.id != "daylight") paletteById("daylight") else it
    }
    return palette
}

/** Web semantics: darkMode "system"|"light"|"dark"; light mode → Daylight. */
@Composable
fun mqColorScheme(themeId: String, darkMode: String): ColorScheme {
    val systemDark = isSystemInDarkTheme()
    val dark = when (darkMode) {
        "light" -> false
        "dark" -> true
        else -> systemDark
    }
    val palette = paletteById(themeId).let {
        if (!dark && it.isDark && it.id != "daylight") paletteById("daylight") else it
    }
    return if (palette.isDark) darkSchemeOf(palette) else lightSchemeOf(palette)
}

private fun darkSchemeOf(p: MqPalette) = darkColorScheme(
    primary = p.accent,
    onPrimary = p.onAccent,
    primaryContainer = p.accent.copy(alpha = 0.24f).compositeOverLocal(p.surface),
    onPrimaryContainer = p.text,
    secondary = p.textMuted,
    onSecondary = p.background,
    background = p.background,
    onBackground = p.text,
    surface = p.background,          // web page surface == bg (cards are explicit)
    onSurface = p.text,
    surfaceVariant = p.surface,
    onSurfaceVariant = p.textMuted,
    surfaceContainer = p.surface,
    surfaceContainerHigh = p.surfaceHigh,
    surfaceContainerHighest = p.surfaceHigh,
    outline = p.outline,
    outlineVariant = p.outline.copy(alpha = 0.6f),
    error = Color(0xFFEF4444),
    onError = Color.White,
)

private fun lightSchemeOf(p: MqPalette) = lightColorScheme(
    primary = p.accent,
    onPrimary = p.onAccent,
    background = p.background,
    onBackground = p.text,
    surface = p.background,
    onSurface = p.text,
    surfaceVariant = p.surface,
    onSurfaceVariant = p.textMuted,
    surfaceContainer = p.surface,
    surfaceContainerHigh = p.surfaceHigh,
    outline = p.outline,
    outlineVariant = p.outline.copy(alpha = 0.6f),
    error = Color(0xFFC92A2A),
    onError = Color.White,
)

private fun Color.compositeOverLocal(base: Color): Color =
    Color(
        red = red * alpha + base.red * (1 - alpha),
        green = green * alpha + base.green * (1 - alpha),
        blue = blue * alpha + base.blue * (1 - alpha),
        alpha = 1f,
    )
""")

# ── Typography + tokens (hand-written, appended) ────────────────────────────
lines.append("""
// ── MQ TYPE SCALE — exact port of globals.css .mq-t-* (Manrope) ────────────
// display 30/800 · page 22/800 · section 15/650 · label 11/700 upper
// track 14/600 · trackSm 13/600 · artist 13/500 · body 13/500
// meta 12/500 · meta2 11/500 · btn 13/600 · nav 12/600 · badge 10/700 upper
// time 12/600 tabular · num 11/600 tabular · menu 13/500

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.sp
import com.mq1.player.R

val Manrope = FontFamily(
    Font(R.font.manrope_400, FontWeight.W400),
    Font(R.font.manrope_500, FontWeight.W500),
    Font(R.font.manrope_600, FontWeight.W600),
    Font(R.font.manrope_700, FontWeight.W700),
    Font(R.font.manrope_800, FontWeight.W800),
)

object MqType {
    val display = TextStyle(fontFamily = Manrope, fontSize = 30.sp, fontWeight = FontWeight.W800, lineHeight = 34.sp, letterSpacing = (-0.25).sp)
    val page = TextStyle(fontFamily = Manrope, fontSize = 22.sp, fontWeight = FontWeight.W800, lineHeight = 27.sp, letterSpacing = (-0.4).sp)
    val section = TextStyle(fontFamily = Manrope, fontSize = 15.sp, fontWeight = FontWeight.W600, lineHeight = 20.sp, letterSpacing = (-0.1).sp)
    val label = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W700, lineHeight = 15.sp, letterSpacing = 1.1.sp)
    val track = TextStyle(fontFamily = Manrope, fontSize = 14.sp, fontWeight = FontWeight.W600, lineHeight = 19.sp, letterSpacing = (-0.1).sp)
    val trackSm = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W600, lineHeight = 17.sp, letterSpacing = (-0.1).sp)
    val artist = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 18.sp)
    val body = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 19.sp)
    val meta = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W500, lineHeight = 17.sp)
    val meta2 = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W500, lineHeight = 15.sp)
    val btn = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W600, lineHeight = 13.sp)
    val nav = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W600, lineHeight = 12.sp)
    val badge = TextStyle(fontFamily = Manrope, fontSize = 10.sp, fontWeight = FontWeight.W700, lineHeight = 10.sp, letterSpacing = 0.8.sp)
    val time = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W600, lineHeight = 12.sp, fontFeatureSettings = "tnum")
    val num = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W600, lineHeight = 13.sp, fontFeatureSettings = "tnum")
    val menu = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 16.sp)
    val bigTime = TextStyle(fontFamily = Manrope, fontSize = 26.sp, fontWeight = FontWeight.W700, lineHeight = 26.sp, letterSpacing = (-0.3).sp, fontFeatureSettings = "tnum")
    val title28 = TextStyle(fontFamily = Manrope, fontSize = 28.sp, fontWeight = FontWeight.W800, lineHeight = 31.sp, letterSpacing = (-0.4).sp)
}

val MqTypography = Typography().let { t ->
    t.copy(
        displayLarge = MqType.display, displayMedium = MqType.display,
        headlineLarge = MqType.page, headlineMedium = MqType.section,
        titleLarge = MqType.track, titleMedium = MqType.trackSm,
        titleSmall = MqType.trackSm,
        bodyLarge = MqType.body, bodyMedium = MqType.body, bodySmall = MqType.meta,
        labelLarge = MqType.btn, labelMedium = MqType.meta, labelSmall = MqType.meta2,
    )
}

// ── MQ SPACING / RADIUS — web design-tokens.css, 4px base ──────────────────
object MqSpace {
    val xs = 4.dp; val sm = 8.dp; val md = 12.dp; val lg = 16.dp
    val xl = 20.dp; val xxl = 24.dp; val xxxl = 32.dp
}

object MqRadius {
    val xs = 4.dp; val sm = 6.dp; val md = 8.dp; val lg = 12.dp
    val xl = 16.dp; val xxl = 24.dp; val xxxl = 32.dp
}
""")

text = "\n".join(lines)
# Kotlin requires imports at the top of the file: hoist every import line
# (the appended typography block carries its own), dedupe, drop the mid-file
# copies, and place them right after the package line.
import re as _re
imports = []
for m in _re.finditer(r"^import .+$", text, flags=_re.M):
    line = m.group(0)
    if line not in imports:
        imports.append(line)
text = _re.sub(r"^import .+\n", "", text, flags=_re.M)
text = _re.sub(r"^(package .+)$", r"\1\n" + "\n".join(imports), text, flags=_re.M, count=1)
# fix imports for dp usage at the end
text = text.replace(
    "import androidx.compose.ui.graphics.Color\n",
    "import androidx.compose.ui.graphics.Color\nimport androidx.compose.ui.unit.dp\n",
    1,
)

out = "/home/z/my-project/android/app/src/main/kotlin/com/mq1/player/ui/theme/MqThemes.kt"
open(out, "w").write(text)
print("Wrote", out, "— themes:", len(themes))
