package com.mq1.player.ui.theme
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.sp
import com.mq1.player.R


/**
 * MQ DESIGN SYSTEM — exact port of the web `src/lib/themes.ts`.
 * GENERATED by scripts/gen_mq_themes.py from the web source of truth;
 * every hex is byte-identical to https://mq1.vercel.app.
 * 23 themes: pick by id, same ids as the web store.
 */
data class MqPalette(
    val id: String,
    val name: String,
    val background: Color,
    val surface: Color,          // web --mq-card
    val surfaceHigh: Color,      // web --mq-card-hover
    val accent: Color,
    val text: Color,
    val textMuted: Color,
    val outline: Color,         // web --mq-border
    val inputBg: Color,
    val playerBg: Color,
    val navBg: Color,           // web --mq-nav-bg (last 2 hex = alpha)
    val isDark: Boolean = true,
    val onAccent: Color = Color(0xFFFFFFFF),
)

private val _Default = MqPalette(
    id = "default", name = "Obsidian",
    background = Color(0xFF0E0E0E), surface = Color(0xFF1A1A1A),
    surfaceHigh = Color(0xFF252525), accent = Color(0xFFE03131),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFF5F5F5), textMuted = Color(0xFFB8B8B8),
    outline = Color(0xFF333333), inputBg = Color(0xFF1A1A1A),
    playerBg = Color(0xFF151515), navBg = Color(0xEE0E0E0E),
    isDark = true,
)

private val _Ocean = MqPalette(
    id = "ocean", name = "Abyss",
    background = Color(0xFF0A1628), surface = Color(0xFF0F2035),
    surfaceHigh = Color(0xFF153050), accent = Color(0xFF0EA5E9),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFE0F2FE), textMuted = Color(0xFF9EC5E8),
    outline = Color(0xFF1E3A5F), inputBg = Color(0xFF0F2035),
    playerBg = Color(0xFF0B1929), navBg = Color(0xEE0A1628),
    isDark = true,
)

private val _Neon = MqPalette(
    id = "neon", name = "Magenta",
    background = Color(0xFF0A0A0A), surface = Color(0xFF141414),
    surfaceHigh = Color(0xFF1E1E1E), accent = Color(0xFFF43F5E),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFCE7F3), textMuted = Color(0xFFCC8899),
    outline = Color(0xFF2A1A2A), inputBg = Color(0xFF141414),
    playerBg = Color(0xFF0D0D0D), navBg = Color(0xEE0A0A0A),
    isDark = true,
)

private val _Sunset = MqPalette(
    id = "sunset", name = "Ember",
    background = Color(0xFF1A100A), surface = Color(0xFF261A10),
    surfaceHigh = Color(0xFF332218), accent = Color(0xFFF97316),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFEF3C7), textMuted = Color(0xFFCC9966),
    outline = Color(0xFF3D2A15), inputBg = Color(0xFF261A10),
    playerBg = Color(0xFF1E1409), navBg = Color(0xEE1A100A),
    isDark = true,
)

private val _Aurora = MqPalette(
    id = "aurora", name = "Borealis",
    background = Color(0xFF0A0F14), surface = Color(0xFF101A22),
    surfaceHigh = Color(0xFF162530), accent = Color(0xFF34D399),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFD1FAE5), textMuted = Color(0xFF7ABBA0),
    outline = Color(0xFF1A3028), inputBg = Color(0xFF101A22),
    playerBg = Color(0xFF0C1519), navBg = Color(0xEE0A0F14),
    isDark = true,
)

private val _Cyberpunk = MqPalette(
    id = "cyberpunk", name = "Neon City",
    background = Color(0xFF0D0015), surface = Color(0xFF1A0025),
    surfaceHigh = Color(0xFF260035), accent = Color(0xFFFF2A6D),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFF0E6FF), textMuted = Color(0xFFB899CC),
    outline = Color(0xFF3A1050), inputBg = Color(0xFF1A0025),
    playerBg = Color(0xFF0A0010), navBg = Color(0xEE0D0015),
    isDark = true,
)

private val _Synthwave = MqPalette(
    id = "synthwave", name = "Retro",
    background = Color(0xFF120A20), surface = Color(0xFF1C1230),
    surfaceHigh = Color(0xFF261A40), accent = Color(0xFFE040FB),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFF3E5F5), textMuted = Color(0xFFAA8ABF),
    outline = Color(0xFF352548), inputBg = Color(0xFF1C1230),
    playerBg = Color(0xFF0F0818), navBg = Color(0xEE120A20),
    isDark = true,
)

private val _Midnight = MqPalette(
    id = "midnight", name = "Eclipse",
    background = Color(0xFF000000), surface = Color(0xFF0A0A0A),
    surfaceHigh = Color(0xFF141414), accent = Color(0xFFFFFFFF),
    onAccent = Color(0xFF000000),
    text = Color(0xFFFFFFFF), textMuted = Color(0xFF999999),
    outline = Color(0xFF1A1A1A), inputBg = Color(0xFF0A0A0A),
    playerBg = Color(0xFF050505), navBg = Color(0xEE000000),
    isDark = true,
)

private val _Black = MqPalette(
    id = "black", name = "AMOLED",
    background = Color(0xFF000000), surface = Color(0xFF080808),
    surfaceHigh = Color(0xFF111111), accent = Color(0xFFE03131),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFE8E8E8), textMuted = Color(0xFF8A8A8A),
    outline = Color(0xFF1A1A1A), inputBg = Color(0xFF080808),
    playerBg = Color(0xFF030303), navBg = Color(0xEE000000),
    isDark = true,
)

private val _Volcano = MqPalette(
    id = "volcano", name = "Volcano",
    background = Color(0xFF1A0A0A), surface = Color(0xFF251010),
    surfaceHigh = Color(0xFF301818), accent = Color(0xFFFF4500),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFFE4C4), textMuted = Color(0xFFCC9980),
    outline = Color(0xFF3D2020), inputBg = Color(0xFF251010),
    playerBg = Color(0xFF1E0E0E), navBg = Color(0xEE1A0A0A),
    isDark = true,
)

private val _Arctic = MqPalette(
    id = "arctic", name = "Arctic",
    background = Color(0xFF0A1520), surface = Color(0xFF101E2E),
    surfaceHigh = Color(0xFF162840), accent = Color(0xFF88CCFF),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFE8F4FF), textMuted = Color(0xFF88B0CC),
    outline = Color(0xFF1A3050), inputBg = Color(0xFF101E2E),
    playerBg = Color(0xFF0C1825), navBg = Color(0xEE0A1520),
    isDark = true,
)

private val _Phantom = MqPalette(
    id = "phantom", name = "Phantom",
    background = Color(0xFF111111), surface = Color(0xFF1C1C1C),
    surfaceHigh = Color(0xFF262626), accent = Color(0xFFA78BFA),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFE8E0F8), textMuted = Color(0xFFAA99CC),
    outline = Color(0xFF2E2E2E), inputBg = Color(0xFF1C1C1C),
    playerBg = Color(0xFF161616), navBg = Color(0xEE111111),
    isDark = true,
)

private val _Daylight = MqPalette(
    id = "daylight", name = "Daylight",
    background = Color(0xFFF8F9FA), surface = Color(0xFFFFFFFF),
    surfaceHigh = Color(0xFFF0F0F0), accent = Color(0xFFC92A2A),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFF212529), textMuted = Color(0xFF6C757D),
    outline = Color(0xFFDEE2E6), inputBg = Color(0xFFFFFFFF),
    playerBg = Color(0xFFFFFFFF), navBg = Color(0xF2F8F9FA),
    isDark = false,
)

private val _Halloween = MqPalette(
    id = "halloween", name = "Halloween",
    background = Color(0xFF0D0A00), surface = Color(0xFF1A1508),
    surfaceHigh = Color(0xFF251E0D), accent = Color(0xFFFF6600),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFDE68A), textMuted = Color(0xFFCCAA44),
    outline = Color(0xFF3D2D00), inputBg = Color(0xFF1A1508),
    playerBg = Color(0xFF120F06), navBg = Color(0xEE0D0A00),
    isDark = true,
)

private val _Newyear = MqPalette(
    id = "newyear", name = "New Year",
    background = Color(0xFF0A0510), surface = Color(0xFF150A20),
    surfaceHigh = Color(0xFF20102E), accent = Color(0xFFFBBF24),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFEF3C7), textMuted = Color(0xFFBBAA88),
    outline = Color(0xFF30253D), inputBg = Color(0xFF150A20),
    playerBg = Color(0xFF0F0818), navBg = Color(0xEE0A0510),
    isDark = true,
)

private val _Valentine = MqPalette(
    id = "valentine", name = "Valentine",
    background = Color(0xFF150810), surface = Color(0xFF200D18),
    surfaceHigh = Color(0xFF2D1420), accent = Color(0xFFF43F5E),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFCE7F3), textMuted = Color(0xFFCC8899),
    outline = Color(0xFF3D1A2A), inputBg = Color(0xFF200D18),
    playerBg = Color(0xFF180A12), navBg = Color(0xEE150810),
    isDark = true,
)

private val _Spring = MqPalette(
    id = "spring", name = "Spring",
    background = Color(0xFF0A120A), surface = Color(0xFF101E10),
    surfaceHigh = Color(0xFF182A18), accent = Color(0xFF4ADE80),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFDCFCE7), textMuted = Color(0xFF88BB88),
    outline = Color(0xFF1A3520), inputBg = Color(0xFF101E10),
    playerBg = Color(0xFF0C150C), navBg = Color(0xEE0A120A),
    isDark = true,
)

private val _Summer = MqPalette(
    id = "summer", name = "Summer",
    background = Color(0xFF151008), surface = Color(0xFF201A0D),
    surfaceHigh = Color(0xFF2D2412), accent = Color(0xFFFACC15),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFEF9C3), textMuted = Color(0xFFBBAA66),
    outline = Color(0xFF3D3010), inputBg = Color(0xFF201A0D),
    playerBg = Color(0xFF181208), navBg = Color(0xEE151008),
    isDark = true,
)

private val _Autumn = MqPalette(
    id = "autumn", name = "Autumn",
    background = Color(0xFF120A05), surface = Color(0xFF1E140A),
    surfaceHigh = Color(0xFF2A1C0F), accent = Color(0xFFD97706),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFEF3C7), textMuted = Color(0xFFBB9966),
    outline = Color(0xFF352510), inputBg = Color(0xFF1E140A),
    playerBg = Color(0xFF150E08), navBg = Color(0xEE120A05),
    isDark = true,
)

private val _Stpatrick = MqPalette(
    id = "stpatrick", name = "St. Patrick",
    background = Color(0xFF050D05), surface = Color(0xFF0A1A0A),
    surfaceHigh = Color(0xFF122412), accent = Color(0xFF22C55E),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFDCFCE7), textMuted = Color(0xFF77BB77),
    outline = Color(0xFF153015), inputBg = Color(0xFF0A1A0A),
    playerBg = Color(0xFF081208), navBg = Color(0xEE050D05),
    isDark = true,
)

private val _Streaming = MqPalette(
    id = "streaming", name = "Streaming",
    background = Color(0xFF121212), surface = Color(0xFF1A1A2E),
    surfaceHigh = Color(0xFF252540), accent = Color(0xFFE53E3E),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFFFFFFF), textMuted = Color(0xFFA0AEC0),
    outline = Color(0x14FFFFFF), inputBg = Color(0xFF1A1A2E),
    playerBg = Color(0xFF0D0D0D), navBg = Color(0xEB121212),
    isDark = true,
)

private val _Easter = MqPalette(
    id = "easter", name = "Easter",
    background = Color(0xFF0F0A12), surface = Color(0xFF1A1220),
    surfaceHigh = Color(0xFF24192E), accent = Color(0xFFC084FC),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFF3E8FF), textMuted = Color(0xFFBB99CC),
    outline = Color(0xFF302040), inputBg = Color(0xFF1A1220),
    playerBg = Color(0xFF120E18), navBg = Color(0xEE0F0A12),
    isDark = true,
)

private val _Blood = MqPalette(
    id = "blood", name = "Blood",
    background = Color(0xFF080404), surface = Color(0xFF140A0A),
    surfaceHigh = Color(0xFF1E0F0F), accent = Color(0xFFCC0000),
    onAccent = Color(0xFFFFFFFF),
    text = Color(0xFFF5E0E0), textMuted = Color(0xFFB07070),
    outline = Color(0xFF2A0E0E), inputBg = Color(0xFF140A0A),
    playerBg = Color(0xFF0C0606), navBg = Color(0xEE080404),
    isDark = true,
)

val mqThemes: List<MqPalette> = listOf(_Default, _Ocean, _Neon, _Sunset, _Aurora, _Cyberpunk, _Synthwave, _Midnight, _Black, _Volcano, _Arctic, _Phantom, _Daylight, _Halloween, _Newyear, _Valentine, _Spring, _Summer, _Autumn, _Stpatrick, _Streaming, _Easter, _Blood)

fun paletteById(id: String): MqPalette =
    mqThemes.firstOrNull { it.id == id } ?: mqThemes.first()


/** Raw web palette access for components that read tokens the M3 scheme
 *  does not carry (inputBg, playerBg, navBg…). Provided by MainActivity. */
val LocalMqPalette = androidx.compose.runtime.staticCompositionLocalOf<MqPalette> {
    error("MqPalette not provided — wrap the tree in CompositionLocalProvider(LocalMqPalette to …)")
}

/** Resolves the palette exactly like mqColorScheme (dark-mode fallbacks). */
@Composable
fun currentMqPalette(themeId: String, darkMode: String): MqPalette {
    val systemDark = isSystemInDarkTheme()
    val dark = when (darkMode) {
        "light" -> false
        "dark" -> true
        else -> systemDark
    }
    val palette = paletteById(themeId).let {
        if (!dark && it.isDark && it.id != "daylight") paletteById("daylight") else it
    }
    return palette
}

/** Web semantics: darkMode "system"|"light"|"dark"; light mode → Daylight. */
@Composable
fun mqColorScheme(themeId: String, darkMode: String): ColorScheme {
    val systemDark = isSystemInDarkTheme()
    val dark = when (darkMode) {
        "light" -> false
        "dark" -> true
        else -> systemDark
    }
    val palette = paletteById(themeId).let {
        if (!dark && it.isDark && it.id != "daylight") paletteById("daylight") else it
    }
    return if (palette.isDark) darkSchemeOf(palette) else lightSchemeOf(palette)
}

private fun darkSchemeOf(p: MqPalette) = darkColorScheme(
    primary = p.accent,
    onPrimary = p.onAccent,
    primaryContainer = p.accent.copy(alpha = 0.24f).compositeOverLocal(p.surface),
    onPrimaryContainer = p.text,
    secondary = p.textMuted,
    onSecondary = p.background,
    background = p.background,
    onBackground = p.text,
    surface = p.background,          // web page surface == bg (cards are explicit)
    onSurface = p.text,
    surfaceVariant = p.surface,
    onSurfaceVariant = p.textMuted,
    surfaceContainer = p.surface,
    surfaceContainerHigh = p.surfaceHigh,
    surfaceContainerHighest = p.surfaceHigh,
    outline = p.outline,
    outlineVariant = p.outline.copy(alpha = 0.6f),
    error = Color(0xFFEF4444),
    onError = Color.White,
)

private fun lightSchemeOf(p: MqPalette) = lightColorScheme(
    primary = p.accent,
    onPrimary = p.onAccent,
    background = p.background,
    onBackground = p.text,
    surface = p.background,
    onSurface = p.text,
    surfaceVariant = p.surface,
    onSurfaceVariant = p.textMuted,
    surfaceContainer = p.surface,
    surfaceContainerHigh = p.surfaceHigh,
    outline = p.outline,
    outlineVariant = p.outline.copy(alpha = 0.6f),
    error = Color(0xFFC92A2A),
    onError = Color.White,
)

private fun Color.compositeOverLocal(base: Color): Color =
    Color(
        red = red * alpha + base.red * (1 - alpha),
        green = green * alpha + base.green * (1 - alpha),
        blue = blue * alpha + base.blue * (1 - alpha),
        alpha = 1f,
    )


// ── MQ TYPE SCALE — exact port of globals.css .mq-t-* (Manrope) ────────────
// display 30/800 · page 22/800 · section 15/650 · label 11/700 upper
// track 14/600 · trackSm 13/600 · artist 13/500 · body 13/500
// meta 12/500 · meta2 11/500 · btn 13/600 · nav 12/600 · badge 10/700 upper
// time 12/600 tabular · num 11/600 tabular · menu 13/500


val Manrope = FontFamily(
    Font(R.font.manrope_400, FontWeight.W400),
    Font(R.font.manrope_500, FontWeight.W500),
    Font(R.font.manrope_600, FontWeight.W600),
    Font(R.font.manrope_700, FontWeight.W700),
    Font(R.font.manrope_800, FontWeight.W800),
)

object MqType {
    val display = TextStyle(fontFamily = Manrope, fontSize = 30.sp, fontWeight = FontWeight.W800, lineHeight = 34.sp, letterSpacing = (-0.25).sp)
    val page = TextStyle(fontFamily = Manrope, fontSize = 22.sp, fontWeight = FontWeight.W800, lineHeight = 27.sp, letterSpacing = (-0.4).sp)
    val section = TextStyle(fontFamily = Manrope, fontSize = 15.sp, fontWeight = FontWeight.W600, lineHeight = 20.sp, letterSpacing = (-0.1).sp)
    val label = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W700, lineHeight = 15.sp, letterSpacing = 1.1.sp)
    val track = TextStyle(fontFamily = Manrope, fontSize = 14.sp, fontWeight = FontWeight.W600, lineHeight = 19.sp, letterSpacing = (-0.1).sp)
    val trackSm = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W600, lineHeight = 17.sp, letterSpacing = (-0.1).sp)
    val artist = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 18.sp)
    val body = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 19.sp)
    val meta = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W500, lineHeight = 17.sp)
    val meta2 = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W500, lineHeight = 15.sp)
    val btn = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W600, lineHeight = 13.sp)
    val nav = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W600, lineHeight = 12.sp)
    val badge = TextStyle(fontFamily = Manrope, fontSize = 10.sp, fontWeight = FontWeight.W700, lineHeight = 10.sp, letterSpacing = 0.8.sp)
    val time = TextStyle(fontFamily = Manrope, fontSize = 12.sp, fontWeight = FontWeight.W600, lineHeight = 12.sp, fontFeatureSettings = "tnum")
    val num = TextStyle(fontFamily = Manrope, fontSize = 11.sp, fontWeight = FontWeight.W600, lineHeight = 13.sp, fontFeatureSettings = "tnum")
    val menu = TextStyle(fontFamily = Manrope, fontSize = 13.sp, fontWeight = FontWeight.W500, lineHeight = 16.sp)
    val bigTime = TextStyle(fontFamily = Manrope, fontSize = 26.sp, fontWeight = FontWeight.W700, lineHeight = 26.sp, letterSpacing = (-0.3).sp, fontFeatureSettings = "tnum")
    val title28 = TextStyle(fontFamily = Manrope, fontSize = 28.sp, fontWeight = FontWeight.W800, lineHeight = 31.sp, letterSpacing = (-0.4).sp)
}

val MqTypography = Typography().let { t ->
    t.copy(
        displayLarge = MqType.display, displayMedium = MqType.display,
        headlineLarge = MqType.page, headlineMedium = MqType.section,
        titleLarge = MqType.track, titleMedium = MqType.trackSm,
        titleSmall = MqType.trackSm,
        bodyLarge = MqType.body, bodyMedium = MqType.body, bodySmall = MqType.meta,
        labelLarge = MqType.btn, labelMedium = MqType.meta, labelSmall = MqType.meta2,
    )
}

// ── MQ SPACING / RADIUS — web design-tokens.css, 4px base ──────────────────
object MqSpace {
    val xs = 4.dp; val sm = 8.dp; val md = 12.dp; val lg = 16.dp
    val xl = 20.dp; val xxl = 24.dp; val xxxl = 32.dp
}

object MqRadius {
    val xs = 4.dp; val sm = 6.dp; val md = 8.dp; val lg = 12.dp
    val xl = 16.dp; val xxl = 24.dp; val xxxl = 32.dp
}
